### ISSUE TITLE
Add a tab of queued/in progress downloads

### ISSUE THREAD

**Issue by RichyZ99** [shaked6540/YoutubePlaylistDownloader#1]
Once you start the download, there is a progress bar and a _Back_ button: if you press the _Back_ button, you return to the home tab, but you can't see what is being downloaded.

I suggest to add a “Videos” section, where you can find everything that has already been downloaded and what is being downloaded at the moment.

**Comment by shaked6540** [comment]
This was implemented in the latest update, thanks for the suggestion! :)
