### ISSUE TITLE
When you maximize the window while it is listing Downloads in the Queue Tab, the screen will get cut off

### ISSUE THREAD

**Issue by Bummbumm6** [shaked6540/YoutubePlaylistDownloader#103]
I don't know how many issues I'm still gonna find maximizing it tbh
![Screenshot_20221216_171304](https://user-images.githubusercontent.com/103200560/208141680-4f814e75-f993-4d4e-a4ab-430af9e42dc2.png)
Don't ask wtf I was downloading

**Comment by shaked6540** [comment]
Thanks for letting me know, I will try to solve it soon. Does it happen only when the program is maximized?

**Comment by shaked6540** [comment]
I've released an update that should fix it, let me know if it did

**Comment by tauniaxd** [comment]
> I've released an update that should fix it, let me know if it did

Hi! This was fine with an older version, but I just updated to the newer one hoping it would fix the login problem (which didn't qwq) and this started again:

![Image](https://github.com/user-attachments/assets/d1d61ce4-c1e3-409c-9d19-a4e555c29726)
