### ISSUE TITLE
New Channels Links dont download

### ISSUE THREAD

**Issue by kissableandres** [shaked6540/YoutubePlaylistDownloader#105]
This links no download in v1.9.3 version
https://www.youtube.com/@LesIngenieurs

**Comment by shaked6540** [comment]
Thanks for the report, I will check it out over the weekend

**Comment by shaked6540** [comment]
Hey, it should be fixed now, please update to v1.9.4 and check if it works

**Comment by kissableandres** [comment]
i am in the 1.9.6 versio and the following problems appear:

1. - By placing the given example: "https://www.youtube.com/@LesIngenieurs" a result actually appears but not that of the channel in question. The result that appears is from the channel: "https://www.youtube.com/@lesingenieursbdi3279"

2.- Placing another example like: "https://www.youtube.com/@Rayi19yt" or "https://www.youtube.com/@YandelBL" does not return results. I imagine that for the same error that the previous bug has. Thank you.

**Comment by shaked6540** [comment]
Should be fixed now, let me know if it works

**Comment by kissableandres** [comment]
its all okay. Thank you.
