### ISSUE TITLE
Feature - Add an option to download the highest quality thumbnail possible.

### ISSUE THREAD

**Issue by nyaasar** [shaked6540/YoutubePlaylistDownloader#106]
This suggestion might sound weird, but yes, there are people, like me, who loves to download them juicy high quality thumbnails.

The app works like a wonder, the only downside is that the downloaded thumbnails are of the lowest quality. This might be trivial, but it still count as a feature.

Bonus, this is the playlist that I just downloaded:
[https://youtube.com/playlist?list=PLCGMFBOVTtiINmOoykSm1alcox6r7QSUN&si=EnSIkaIECMiOmarE](https://youtube.com/playlist?list=PLCGMFBOVTtiINmOoykSm1alcox6r7QSUN&si=EnSIkaIECMiOmarE)

**Comment by shaked6540** [comment]
The thumbnail I use are the same one that should be in the video suggestion that YouTube uses, where do you get a higher quality thumbnail from?

**Comment by nyaasar** [comment]
Well, they can be downloaded from a third party website.
https://www.youtubethumbnaildownloader.com/
or by doing this:

Video Sample
https://www.youtube.com/watch?v=SW12QDW48cA

Highest Quality
> https://img.youtube.com/vi/SW12QDW48cA/maxresdefault.jpg

Medium Quality
> https://img.youtube.com/vi/SW12QDW48cA/hqdefault.jpg

Low Quality
> https://img.youtube.com/vi/SW12QDW48cA/mqdefault.jpg


This is visual comparison for **maxresdefault** and **hqdefault** image as an example,
![image](https://user-images.githubusercontent.com/54396528/209907004-86cec7e1-2180-4754-8226-5af3da9e74b2.png)

and this is the one that this app downloaded.
![image](https://user-images.githubusercontent.com/54396528/209907139-a03816d3-4043-40cb-8272-75d72a3bc10b.png)

**Comment by nyaasar** [comment]
And of course it will be much more preffered if the app can download each thumbnail in the playlist individually for each video, because sometimes, the thumbnail are different.

So, what do you think?

**Comment by shaked6540** [comment]
Thanks for letting me know about the higher quality options, I will add it this weekend

**Comment by shaked6540** [comment]
I've released a new version that uses the highest quality thumbnail, let me know if it works

**Comment by nyaasar** [comment]
> I've released a new version that uses the highest quality thumbnail, let me know if it works

It works!
![image](https://user-images.githubusercontent.com/54396528/210144716-15fbda1e-877e-447d-9297-713a04d2a6a8.png)

Thank you for adding this feature. And happy new year!
