### ISSUE TITLE
Doesn't fetch data about playlist.

### ISSUE THREAD

**Issue by samk1r0** [shaked6540/YoutubePlaylistDownloader#109]
When I paste a link to the playlist most of times it doesn't fetch data about it, so I have to download every video inside the playlist one by one. a link from the screenshot: https://youtube.com/playlist?list=OLAK5uy_nrO7jmxxFUnFAneYpErd7k9pJ9bFhaCQI
![image](https://user-images.githubusercontent.com/36104994/210608158-98681a6e-ea81-4648-96c3-39e89af1e9fa.png)

**Comment by shaked6540** [comment]
I've released an update that should fix this issue

**Comment by samk1r0** [comment]
Now it fetches data however after clicking download button it doesn't download the content

**Comment by shaked6540** [comment]
Sorry for this, it should be fixed now in 1.9.6

**Comment by samk1r0** [comment]
everything works just fine! No reason to excuse.
