### ISSUE TITLE
closed caption

### ISSUE THREAD

**Issue by HerculeLiu** [shaked6540/YoutubePlaylistDownloader#110]
Hi, I try to download video with closed caption, but sometimes it doesnt work.
the video I want to download has the language subtitle that I want.

So, do you know what problem it is? can you fix it?

Thanks.

**Comment by shaked6540** [comment]
I can't know what is the problem if you don't share the video and the language

**Comment by HerculeLiu** [comment]
https://www.youtube.com/watch?v=hJg1UZnU7Hg&list=PLA281bxFYhI3b9YU6FcmArAcfbWC7DAi3&index=1
this is the video I want to download, and with Chinese subtitle.

thanks.

**Comment by shaked6540** [comment]
I only see English captions for this video. Maybe you got confused by YouTube's auto translate option? 
![image](https://user-images.githubusercontent.com/13851815/213585946-32e88fef-d71d-45f0-bd7f-943382d67780.png)

**Comment by HerculeLiu** [comment]
I see, Thanks. 
Sorry for disturbing you.
