### ISSUE TITLE
File name pattern not working

### ISSUE THREAD

**Issue by Kelsinga** [shaked6540/YoutubePlaylistDownloader#115]
The file name pattern doesn't seem to be working.
Either with a single download or playlist it just saves the title, not per example "$index. $title - $artist" or just "$index"
I haven't tried other patterns

And could you please add in the README that these are the patterns available for the title.
$title
$index
$artist
$songtitle
$channel
$videoid
$playlist
$genre

**Comment by shaked6540** [comment]
Can you share the settings and videos/playlists you tried downloading and the feature didn't work?
The description of the feature is in the Help page, the README isn't supposed to be a wiki of the features

**Comment by Kelsinga** [comment]
Settings
![image](https://user-images.githubusercontent.com/29175880/217768520-01718d19-62d7-4eb8-b7e2-29a89ae0de05.png)


https://www.youtube.com/watch?v=J6UWnzWdZmQ&list=PLAbMhAYRuCUhawCEV2oXZGrienoKTN16X

The File name pattern doesn't seem to work.
with $index. $title - $artist I expected the first video to be named: "1. Sailing Era (Zero Punctuation) - The Escapist"
and with $index to be "1"

Yet in both cases it became "Sailing Era (Zero Punctuation)"

**Comment by shaked6540** [comment]
I found the problem and fixed it in the latest update (version 1.9.8 - make sure you update the program before trying again)

Also, it looks like you're using the wrong variables, if you wanted it to be "1. Sailing Era (Zero Punctuation) - The Escapist" you should have entered "$index. $title - $channel"

**Comment by Kelsinga** [comment]
Yes, It's fixed.
Thanks
