### ISSUE TITLE
Download throws error in newest version

### ISSUE THREAD

**Issue by stepframe-design** [shaked6540/YoutubePlaylistDownloader#119]
Hi :)

With the latest release 1.9.10, downloads dont work for me anymore. It just skips the track, and at the end shows the following error: 
"cannot access a closed stream" 

with release 1.9.9 it still works

I tried running as administrator and tested several drives, but still the same error.

**Comment by shaked6540** [comment]
I will check it out

**Comment by shaked6540** [comment]
Should be solved in 1.9.11. Please let me know if it works

**Comment by stepframe-design** [comment]
Yes, works like a charm again! Thank you!
