### ISSUE TITLE
Allow selecting text in the error dialog

### ISSUE THREAD

**Issue by shaked6540** [shaked6540/YoutubePlaylistDownloader#121]
It would be very neat if the list of errors that shows at the completion of a playlist download with the links that couldn't download would be selectable or able to exported to a file (as opposed to manually typing them in a notepad) so that we could easily keep a record of them and possibly attempt again later rather than just at that moment. Thank you!

_Originally posted by @Kazzymax in https://github.com/shaked6540/YoutubePlaylistDownloader/discussions/120_

**Comment by Kazzymax** [comment]
Thank you for taking this into consideration and also better wording my description to be more accurate. I wanted to add that this is an Excellent program and just as others have mentioned before, about the only one that actually does the job! :)

**Comment by shaked6540** [comment]
Added in version 1.9.12

**Comment by Kazzymax** [comment]
Thank you so much!  While trying it out, I realized it might even just be easier to have a button that copies it all labeled Copy to Clipboard or Export (error list/links) as TXT. Would that be possible?

**Comment by shaked6540** [comment]
Yes, I'll add a button to copy it to clipboard and another one to export it to a txt file

**Comment by shaked6540** [comment]
I added it, however I'm not releasing a new version yet because this is a very small feature and I don't want to annoy people with too many updates. Here is the link to download the program with the new feature, and don't worry, it will be included in the next version as well: https://github.com/shaked6540/YoutubePlaylistDownloader/releases/download/1.9.12/YoutubePlaylistDownloader-patch.exe


Let me know if that's what you wanted, and if not feel free to re-open this issue
