### ISSUE TITLE
Playlist up to date

### ISSUE THREAD

**Issue by GangstaPichu** [shaked6540/YoutubePlaylistDownloader#125]
Have in the keep channel stuff up to date support for checking a playlist. So, that if something new is added it will just download it.

**Comment by shaked6540** [comment]
Sorry I dont understand what you're saying

**Comment by Bummbumm6** [comment]
He means if there is a new item added in a playlist, it will automatically download it.. i don't think that's possible..

**Comment by shaked6540** [comment]
It used to be possible with the subscriptions feature but youtube removed the date from the video information (I'm only getting "x days ago", "x months ago" or "x years ago" instead of the absolute date) so its not possible anymore

sorry
