### ISSUE TITLE
wont start download

### ISSUE THREAD

**Issue by peanutbutterman19** [shaked6540/YoutubePlaylistDownloader#127]
i put the link into the text box and the download button doesnt light up,  i try putting it into bulk download and the button lights up and i click it and it takes me to queue and nothing is there its just a blank screen
![image_2023-03-19_183716435](https://user-images.githubusercontent.com/128333130/226221165-a1583ad3-83b9-472b-9286-73378033b9f9.png)

![image_2023-03-19_183740199](https://user-images.githubusercontent.com/128333130/226221181-188feccf-b99b-4544-ba28-8f179b3355ee.png)

![image_2023-03-19_183757334](https://user-images.githubusercontent.com/128333130/226221197-47b22e89-05cb-4eae-a2e2-c03388a332d3.png)

![image_2023-03-19_184101226](https://user-images.githubusercontent.com/128333130/226221407-4345c43c-d143-453d-97f8-7543dbbf0dcd.png)

**Comment by shaked6540** [comment]
I will look into it tomorrow, can you paste the link as a comment so its easier for me to check it?

**Comment by peanutbutterman19** [comment]
https://www.youtube.com/playlist?list=PLZFHrATaoSVrvt4mOdzCsUQC2o56DR3gI

**Comment by peanutbutterman19** [comment]
ive also tried it with a larger playlist but it still wont work

**Comment by shaked6540** [comment]
> https://www.youtube.com/playlist?list=PLZFHrATaoSVrvt4mOdzCsUQC2o56DR3gI

This works for me, are you sure you're using the latest version? Make sure the version in the About page is 1.9.12 or later

**Comment by shaked6540** [comment]
Closing as there has been no response for over a week and I can't reproduce it
