### ISSUE TITLE
nothing in downloads folder 

### ISSUE THREAD

**Issue by mahaveergautam83** [shaked6540/YoutubePlaylistDownloader#129]
please solve this error i lost my 30 GB mobile data on this  and found nothing in downloads folder

**Comment by shaked6540** [comment]
You should have read the README.md file, or at least looked in other issues before opening a new one. I leave this issue open because of this https://github.com/shaked6540/YoutubePlaylistDownloader/issues/93

Also note that this isn't a bug, its just windows being over protective
