### ISSUE TITLE
Missing reference 

### ISSUE THREAD

**Issue by luisduenas** [shaked6540/YoutubePlaylistDownloader#13]
Hi, nice project!
I tried to build the solution but there's a missing reference to "taglib-sharp" in packages.config.
Where can i get the same version of taglib-sharp you are using?
I tried downloading the NuGet package available but it's not compatible (or at least the version i downloaded wasn't).
Thanks in advance.

**Comment by shaked6540** [comment]
I took it from here: https://github.com/mono/taglib-sharp

**Comment by shaked6540** [comment]
If you have the program installed you can also get the reference to it from the install directory, its called `taglib-sharp.dll`

**Comment by shaked6540** [comment]
Were you able to solve the issue?

**Comment by luisduenas** [comment]
Sorry for the late response, issue solved, downloaded the repo and took the dll from there, thanks!

**Comment by shaked6540** [comment]
Glad it worked out :)
