### ISSUE TITLE
פורמט הורדה

### ISSUE THREAD

**Issue by elchanan9** [shaked6540/YoutubePlaylistDownloader#133]
היי האם התוכנה תומכת בהורדה כפורמט mp4 או רק mkv?
נ.ב. התוכנה ממש טובה שימושית עם מלא אופציות וקלה לתפעול תודה רבה לך!!!!!!!!!!!!!!

**Comment by shaked6540** [comment]
היי, כרגע רק mkv כי יש קומבינציות של אודיו + וידאו שלא נתמכים על ידי mp4. 
הפעם האחרונה שבדקתי את זה הייתה ב2018 בערך אז אולי דברים השתנו מאז

**Comment by elchanan9** [comment]
רק עכשיו אני אוחז שאת ישראלית 
ואו תקשיבי תוכנה מטורפת!!!!!!! הרבה יותר טובה ונוחה לשימוש אפילו מאלה שבתשלום פירסמתי את זה [פה](חרקיעה)

**Comment by shaked6540** [comment]
תודה רבה ופסח שמח :)

אולי בחול המועד אוסיף תמיכה בmp4, אבדוק איך זה מסתדר

**Comment by elchanan9** [comment]
יאלה זה ישלים את התוכנה
 פסח כשר ושמח 😊 !!

**Comment by elchanan9** [comment]
אגב פירסמתי את התוכנה גם [פה](https://mitmachim.top/topic/52225/%D7%A9%D7%99%D7%AA%D7%95%D7%A3-%D7%94%D7%95%D7%A8%D7%93%D7%94-%D7%9E%D7%99%D7%95%D7%98%D7%99%D7%95%D7%91-%D7%94%D7%9B%D7%99-%D7%98%D7%95%D7%91%D7%94/7?_=1680259734850) וכמובן כולם נהנו
