### ISSUE TITLE
After new update 

### ISSUE THREAD

**Issue by Khalid-Hani** [shaked6540/YoutubePlaylistDownloader#136]
The playlist link does not trigger a download after being entered into the designated box following a recent update to the app, resulting in the inability to download playlists. 

Nevertheless, thank you for providing this exceptional application.

**Comment by shaked6540** [comment]
Can you send the link?

**Comment by Khalid-Hani** [comment]
https://youtube.com/playlist?list=PL8pYI62gCNsXVvv1jWd-t3O8_l45Vj65x



This one ... and many other links

**Comment by shaked6540** [comment]
I just tried and it worked for me, could it be that some anti virus software is blocking access for my program? 
You could also upload the log files so I can have a bit more information 

To get the log files, press WinKey+R and type  `%appdata%/Youtube Playlist Downloader` into it. The log file is called Errors.txt

**Comment by Khalid-Hani** [comment]
That's strange ---- It seems to be functioning correctly at present. When attempting to download the same file, it is now downloading successfully. 

Generally, I attached the error files you requested.
[Errors.txt](https://github.com/shaked6540/YoutubePlaylistDownloader/files/11163801/Errors.txt)

**Comment by shaked6540** [comment]
I'm glad it was solved, from the log file it looks like you had internet problems, the program tried to reach youtube but it did not receive any answer for more than 100 seconds. 

If you'll have any problems in the future feel free to open a new issue :)
