### ISSUE TITLE
App Launch is failing

### ISSUE THREAD

**Issue by RdotO** [shaked6540/YoutubePlaylistDownloader#137]
Since one of the newer updates I get an error message saying "You must install or update .NET to run this application. Framework: 'Microsoft.AspNetCore.App', version '7.0.0' (x64)".  The downloader always worked without problems but now I get this error even after reinstalling the latest .NET 7.0 Desktop Runtime.

**Comment by shaked6540** [comment]
Try installing it manually from https://dotnet.microsoft.com/en-us/download/dotnet/7.0 
make sure you use version 7.0.0 and not any later version

**Comment by WashedRock** [comment]
> Since one of the newer updates I get an error message saying "You must install or update .NET to run this application. Framework: 'Microsoft.AspNetCore.App', version '7.0.0' (x64)". The downloader always worked without problems but now I get this error even after reinstalling the latest .NET 7.0 Desktop Runtime.

its not working because your downloading the wrong one, you need to install " 'Microsoft.AspNetCore.App', version '7.0.0' (x64)"  aka  [aspnetcore-runtime-7.0.0-win-x64](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-7.0.0-windows-x64-installer)

**Comment by RdotO** [comment]
Yes this did the trick, thank you!
