### ISSUE TITLE
add video number as prefix to the title

### ISSUE THREAD

**Issue by Ahmed-Soli** [shaked6540/YoutubePlaylistDownloader#142]
I download many playlists and it would be very helpful if you can add the video number as a prefix to the title 
for example :
1- introduction.ext
2- ...
and so on so that I would know which video comes first .

**Comment by shaked6540** [comment]
You can do that by going into options and setting the file name pattern to `$index - $title`. You can find out more about the file name pattern feature in the Help page, in the File name pattern tab: 

![image](https://user-images.githubusercontent.com/13851815/234608201-28e934d3-e6c1-406b-9db7-5faba632bb60.png)



This is how the settings should look like for you: 
![image](https://user-images.githubusercontent.com/13851815/234608550-c42841ea-135d-4a86-8213-45f3a3ad16e2.png)

**Comment by Ahmed-Soli** [comment]
Thank you, That works .
