### ISSUE TITLE
Playlist doesn`t show up

### ISSUE THREAD

**Issue by DBsTrash** [shaked6540/YoutubePlaylistDownloader#145]
When i paste the playlist link, nothing happens, tried running as admin and it also didnt work.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/115326868/236508118-5fca8475-a2c4-47d0-8d11-e9c5ba3cbb22.png">

Thanks in advance!

**Comment by shaked6540** [comment]
Can you send the link here?

**Comment by cristianst85** [comment]
@DBsTrash, try using the latest version (1.9.16). For me, it works.

https://www.youtube.com/playlist?list=PLF693A00B1C99E549

![image](https://user-images.githubusercontent.com/12585988/236626867-f8da73a5-0298-41df-9011-d8f4030c52a2.png)

**Comment by DBsTrash** [comment]
for some rea
