### ISSUE TITLE
Feature Request: support for adding the video ID to the title

### ISSUE THREAD

**Issue by Johndpete316** [shaked6540/YoutubePlaylistDownloader#154]
Similar to how you have the title as $title for a customizable filename, please add the youtube video ID as an option. 

ex:
`$title - $id`
`return to monke - I6qQG0EUzcw`

that way its easier to use this tool with metadata plugins for Plex or Jellyfin that require the video ID to be in the title.

**Comment by shaked6540** [comment]
I'll try to add it in the next version, I might be able to do it this week

**Comment by shaked6540** [comment]
I just checked and its already available, use `$videoid` 

For all available parameters look in Help->File name pattern
![image](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/13851815/af10adb9-0af9-4751-84ab-6483481c920b)
