### ISSUE TITLE
Prompt to install .NET Framework even after installation

### ISSUE THREAD

**Issue by faizxmohammad** [shaked6540/YoutubePlaylistDownloader#156]
I downloaded  and installed the installer  on my PC , then the App prompts me to install .net framework in my PC , but no matter how many times i try to install the .net framework the app doesn't recognizes that i have .net framework installed and asks me to download it again and again.

<img width="471" alt="issue_1" src="https://github.com/shaked6540/YoutubePlaylistDownloader/assets/81904684/a23b662d-50bc-41f8-96b3-247a3e5da4a8">
<img width="380" alt="issue_2" src="https://github.com/shaked6540/YoutubePlaylistDownloader/assets/81904684/6705816b-845b-447c-8705-b9d1e292356f">

**Comment by shaked6540** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-7.0.5-windows-x64-installer


Try to install it manually from here

**Comment by faizxmohammad** [comment]
Did exactly what you did the app is working fine , the only problem is the playlist which i downloaded is not visible , then i changed the installation directory the videos still aren't there.
<img width="960" alt="not downloaded" src="https://github.com/shaked6540/YoutubePlaylistDownloader/assets/81904684/0775e7f8-72df-4062-97fe-dbb4c9e9b565">
<img width="960" alt="not downloaded2" src="https://github.com/shaked6540/YoutubePlaylistDownloader/assets/81904684/a23c3b07-ab83-4b51-ac20-7250c4425d52">
<img width="960" alt="not downloaded3" src="https://github.com/shaked6540/YoutubePlaylistDownloader/assets/81904684/2a925926-8a45-417a-b857-be27f036f57c">

**Comment by shaked6540** [comment]
Did you try running it as administrator?

**Comment by faizxmohammad** [comment]
Yes , Just ran it as administrator after reading the readme , only after running the app as administrator the videos are getting saved , kind a bug i think if videos are not getting saved without running as administrator ,because it is expected the app to run fine without this permissions , hoping this to be resolve soon.
