### ISSUE TITLE
Feature Request: Number the downloaded files .

### ISSUE THREAD

**Issue by KylinGuo** [shaked6540/YoutubePlaylistDownloader#160]
It would be nice if there is an option that allows me to number the downloaded files when I download a playlist. One example is as follows. 
```
001_file-xxx.mp4
002_file-xxx.mp4
...
999_file-xxx.mp4
```

**Comment by shaked6540** [comment]
You can already do that, look at the file name pattern tab in the Help page

**Comment by KylinGuo** [comment]
> You can already do that, look at the file name pattern tab in the Help page

Thank you!
