### ISSUE TITLE
I cannot find files using "Open destination folder". 

### ISSUE THREAD

**Issue by KylinGuo** [shaked6540/YoutubePlaylistDownloader#161]
After finished downloading, I cannot find files using "Open destination folder". I am using Windows 11. "Open destination folder" direct me to 
```
C:\Users\<UserName>\Videos\Captures
```
However, no files are located here. The downloaded files are actually placed at 
```
C:\Users\<UserName>\AppData\Local\Temp\YoutubePlaylistDownloader
```

**Comment by shaked6540** [comment]
If the files don't show up after you download a playlist, try running the program as administrator or change the save directory to a different drive! (C drive is usually protected by windows, save it under D or any other drive)

**Comment by KylinGuo** [comment]
> If the files don't show up after you download a playlist, try running the program as administrator or change the save directory to a different drive! (C drive is usually protected by windows, save it under D or any other drive)

Thank you!
