### ISSUE TITLE
[Improve feature] Instead of 2-step closing process show it only when downloading is in progress or incomplete!!

### ISSUE THREAD

**Issue by Droyk** [shaked6540/YoutubePlaylistDownloader#17]
I hate this!!
![image](https://user-images.githubusercontent.com/15848350/52071621-64104780-25a9-11e9-828b-208808989c26.png)

Show it only when there's a downloading in progress that's it.

**Comment by shaked6540** [comment]
I'll add an option to disable it in the settings, expect it over the weekend. I will update when it's ready

**Comment by shaked6540** [comment]
Added, sorry for the delay
