### ISSUE TITLE
Video saves in webm I would like it to save in mp3 or m4a

### ISSUE THREAD

**Issue by Ryanqqqq** [shaked6540/YoutubePlaylistDownloader#174]
whenever i use this it either ends up converting the files to webm files which i cant use i dont understand what  im doing wrong also i saw a solution with turning off "turn off download clean audio" but no files end up downloading anywhere i can find (i think i looked everywhere)

ps: ive tried running in admin aswell to no luck still either no files or webm

![image](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/140095562/43caaacd-89ee-4c24-964b-5573b76468f7)

**Comment by shaked6540** [comment]
Remove the "download clean audio" checkbox and it will convert to mp3. That checkbox says it will not convert to any format and will keep the audio clean

**Comment by Ryanqqqq** [comment]
yo bro i did that but for some reason i cant find where the files download when i do that

**Comment by Ryanqqqq** [comment]
ive changed save location to two differnt drives while in admin and it still wont download files, it only starts to download when i check the download clean audio box but then we run into the other issue lol

**Comment by Ryanqqqq** [comment]
i restarted my pc and its working perfectly sorry for the hassle
