### ISSUE TITLE
Paste in video link or playlist link, nothing happens

### ISSUE THREAD

**Issue by kmcbest** [shaked6540/YoutubePlaylistDownloader#175]
And if I paste a link into bulk download, after 1 minute or so, there's an error:

Here is a list of the videos that could not be downloaded, and the reason why: 
https://www.youtube.com/watch?v=9sBuwnmeJcQ Reason: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

I'm in China and I'm using proxy to access Youtube. I suppose the program doesn't look into my PC's proxy setting? But there isn't a proxy setting option in this program either?

**Comment by shaked6540** [comment]
Hey, the program doesn't currently work with proxy, sorry.

**Comment by kmcbest** [comment]
But it worked a while ago, with the same settings (Clash as system proxy, in Windows 10)

**Comment by shaked6540** [comment]
I dont do any special handling of proxy settings, so I dont know what is going on. If it worked and now it doesn't work, it might be a problem with youtube or your proxy, I can't know 

Maybe try downloading later, or try to use another downloader and see if you still can't download
