### ISSUE TITLE
produces separate files, 1 for video, 1 for audio

### ISSUE THREAD

**Issue by quasar-cod** [shaked6540/YoutubePlaylistDownloader#176]
![image](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/128190911/f50fe7c1-b136-4ba3-82e1-81c6f91c7d9a)

**Comment by shaked6540** [comment]
This is the temp location, it downloads the video, audio and cover picture and then merges it and moves it to the save location. If the files dont show up in your save location run the program as administrator, or read the bold line in the readme file

**Comment by quasar-cod** [comment]
my win profile is administrator, anyway I resolved using an external drive, thanks a lot
