### ISSUE TITLE
Nothing Downloaded

### ISSUE THREAD

**Issue by ILaggd** [shaked6540/YoutubePlaylistDownloader#179]
I wanted to download a youtube playlist as MP3 and waited 30 mins. It did not download anything, leaving the destination folder empty.

**Comment by ILaggd** [comment]
I am also somehow getting infinite MiB/s

**Comment by shaked6540** [comment]
Check out https://github.com/shaked6540/YoutubePlaylistDownloader/issues/93 and see if it helps

**Comment by ILaggd** [comment]
It worked, thanks. Jesus Christ, your app is actually amazing! I thought it
was fake bro! Excellently made!
