### ISSUE TITLE
[Feature Request] Open folder after downloading the video.

### ISSUE THREAD

**Issue by Droyk** [shaked6540/YoutubePlaylistDownloader#18]
As it stands now YPD doesn't have any feature to let the user open the download directory. 
add a setting to automatically open the download directory when YPD finishes downloading the files. 
Remember to add this functionality only on the downloading page don't add this on setting page.

There are 2 versions of this feature so let's just make a todo list

- [x] Add an option to automatically open destination folder on the downloading page.

- [x] add an option to manually open the destination folder when downloading finishes

**Comment by shaked6540** [comment]
Done and done, sorry for the delay

**Comment by Korb** [comment]
> add an option to manually open the destination folder when downloading finishes

I agree that it is missing the `Open containing folder` function for each download in the "Queue" tab. Currently, YouTube Playlist Downloader v1.924 does not have this feature. The only action you can do with a download is to delete it with the green cross on the left side.

**Comment by shaked6540** [comment]
> > add an option to manually open the destination folder when downloading finishes
> 
> I agree that it is missing the `Open containing folder` function for each download in the "Queue" tab. Currently, YouTube Playlist Downloader v1.924 does not have this feature. The only action you can do with a download is to delete it with the green cross on the left side.

It will open the containing folder if you double click the item in the queue. You can click anywhere to trigger it (except on the delete button of course)
