### ISSUE TITLE
Playlists with unavaliable videos are only displaying the avaliable videos

### ISSUE THREAD

**Issue by michelle1574** [shaked6540/YoutubePlaylistDownloader#187]
This also counts for downloading region-locked videos as well.

**Comment by shaked6540** [comment]
If the video is unavailable, how do you expect the program to download it?

**Comment by michelle1574** [comment]
It's a region locked video!

**Comment by shaked6540** [comment]
The program runs on your computer and uses your network, so its in the same region as you. I can't make it download unavailable videos
