### ISSUE TITLE
Can't find downloaded videos

### ISSUE THREAD

**Issue by pashmak73** [shaked6540/YoutubePlaylistDownloader#19]
Hi, thanks for this amazing app.
I downloaded some videos to test your app.
the application says `ALL DONE` and in `Queue` tab I can see all of them is downloaded with 100%. but I can't find it in my videos folder. why is that?
I've also changed the save folder and tried again with no luck.

**Comment by shaked6540** [comment]
Did the problem solve itself? I see you closed this issue but you didn't say if you managed to solve it or not
