### ISSUE TITLE
Only format is webm for some reason

### ISSUE THREAD

**Issue by ayacu57** [shaked6540/YoutubePlaylistDownloader#197]
First of all I would like to thank you soooo much for sharing this beautiful program with us :).
Unfortunately, when I tried to download a playlist and changed the audio options to mp3, but all I get are webm files :(
![Bild_2023-10-15_225432985](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/148012174/9a02094c-c25d-4e82-99c5-4a2af42154cf)

**Comment by shaked6540** [comment]
Its because you marked "Download clean audio, without converting to any format". Uncheck that. Also, make sure to select mp3 in the convert drop down, it looks like its set as "wav"

**Comment by ayacu57** [comment]
Thank you sooo much! 
I wish there were more kind people like you in the world ʅ（◞‿◟）ʃ

**Comment by shaked6540** [comment]
Thanks for the kind words, glad it worked out :)
