### ISSUE TITLE
Sometimes it fails a file

### ISSUE THREAD

**Issue by NastyFlytrap** [shaked6540/YoutubePlaylistDownloader#200]
For example i downloaded this playlist, with the setting to convert it to ogg and a handful of videos just dont get converted even when i specifically retry them by themselves

https://www.youtube.com/playlist?list=PLRxygl-iuYKicUSk4DUNVkdDVB94xB_2q
Azteca post apocalypse for example will always download as mp4 despite my video settings being set to mkv and audio to ogg and it needing to convert it to ogg. It doesnt convert it to ogg, and even if it downloaded it as a video its still not saving it as the correct video format

**Comment by shaked6540** [comment]
Can you post a screenshot of your download options?

**Comment by NastyFlytrap** [comment]
![image](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/43176063/1af90de4-a1bf-4830-92cb-becd38ef7295)
Also, i believe i figured out the issue.

It does seem to be audio, but for some reason its mp4a at 44100 hz instead of the ogg 48000, while the file itself uses the mp4 format instead of ogg, or any other audio format

Also, i selected 192khz, so why isnt it using that?

**Comment by shaked6540** [comment]
You selected "download clean audio, without converting to  any format" which is why its downloading without converting. Uncheck that and it will work as expected

**Comment by NastyFlytrap** [comment]
> You selected "download clean audio, without converting to any format" which is why its downloading without converting. Uncheck that and it will work as expected

I understand, but why are 98% of these webm, what i assume to be 'clean audio' while some are mp4? Shouldnt all of them be webm?

**Comment by NastyFlytrap** [comment]
I see. Well, sorry for bothering you i guess
