### ISSUE TITLE
FUCK HAMAS, NICE OCCUPATION , FUCK PALESTINE 

### ISSUE THREAD

**Issue by NadeemAraman** [shaked6540/YoutubePlaylistDownloader#201]
THANK U AND THANK UR CODE XD

**Comment by shaked6540** [comment]
Thank you for your supoprt, please donate at https://www.ufis.org.il/en/donation-en/ !

**Comment by CREED404** [comment]
hhh nice OCCUPATION you say

**Comment by Memerguygoogle** [comment]
what???
