### ISSUE TITLE
Yo i keep bumping into this issue with downloading some files (but its becoming more common)

### ISSUE THREAD

**Issue by Ryanqqqq** [shaked6540/YoutubePlaylistDownloader#209]
i can download a the majourity playlist just fine but for some reason some videos have the error message.

![image](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/140095562/89a16589-95d7-43d9-beb5-2041ce365bd6)

https://youtu.be/MNll1BaskLA

https://youtu.be/JvEhPIRtk9M

https://youtu.be/KepgJld9O2w

https://www.youtube.com/watch?v=nZKhApFCWO8

These are some of the links i cant download with this softwear, i don't think its video length because ive downloaded longer.
 
im running my programm in admin, ive redownloaded the softwear, and it works for other links id say like 80/20. but its becoming more common.
 
![image](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/140095562/d9f9302b-f3a1-4c5c-8cd4-feca0e058686)

These are the settings im currently running, I understand this programm is on halt don't worry about replying. its cool man

Woah something really weird i noticed by accident is it happened to videos that previously before i updated to the latest version worked just fine

https://music.youtube.com/watch?v=4nm_we0JzeU&si=UTVRM6CJB1GspY1D

i downloaded this one a while ago but now it says the issue above. very weird

**Comment by shaked6540** [comment]
I'll try to check this as soon as I have time, it won't be soon though, sorry :/

**Comment by Ryanqqqq** [comment]
dont worry man your good
________________________________

**Comment by Ryanqqqq** [comment]
don't worry man your good

**Comment by Ryanqqqq** [comment]
I fixed it. i reinstalled the aplication to a differnt drive and ran it without admin and it fixed the issue for some reason? not sure why but if anyone has a similar issue this might work for them aswell
