### ISSUE TITLE
Sequence contains no elements

### ISSUE THREAD

**Issue by Slessmanman** [shaked6540/YoutubePlaylistDownloader#22]
Upon trying to download any playlist, it lists off most of the titles, stops, and gives an error of "Sequence contains no elements" for each item.

**Comment by shaked6540** [comment]
I will start working on this tomorrow, thanks for letting me know about this issue

**Comment by shaked6540** [comment]
I partially fixed it, regular videos and playlists should download fine, but large playlists or channels might sometimes not return all videos. (it will return most of them though) 

Hopefully, this will be solved by the end of the week

**Comment by shaked6540** [comment]
The problem seems to be fixed, please re-open this issue if it happens again :)
