### ISSUE TITLE
Application crash upon opening destination folder

### ISSUE THREAD

**Issue by Slessmanman** [shaked6540/YoutubePlaylistDownloader#23]
After the video is downloaded and converted, clicking the "Open destination folder" option results in a crash, with an error reading _**"YoutTube Playlist Downloader: YoutubePlaylistDownloader.exe...** The exception unknown software exception (0xe0434352) occured in the application at location 0x76725ef8"_

**Comment by shaked6540** [comment]
I've released an update that should fix it, let me know if it still happens

**Comment by Slessmanman** [comment]
Looks good. Thank you lots +1:
