### ISSUE TITLE
Bug: 403 response status code doesn't indicate success!!

### ISSUE THREAD

**Issue by Droyk** [shaked6540/YoutubePlaylistDownloader#25]
![2019-08-06_8-08-39](https://user-images.githubusercontent.com/15848350/62507305-85384600-b821-11e9-93f0-f9299c41a5f1.png)
v1.804

link used: https://www.youtube.com/watch?v=hSbBf4REAA8

**Comment by shaked6540** [comment]
Does it happen with other videos as well? I'll not be home until August 9th so I can't check it out right now

**Comment by Droyk** [comment]
Yup, it does happen with some other age-restricted videos aswell.

**Comment by shaked6540** [comment]
I've released an update that should fix this, let me know if its still happening

**Comment by Droyk** [comment]
Fixed!!

**Comment by Droyk** [comment]
Fixed!!
