### ISSUE TITLE
Installer is getting flagged as potentially risky software 

### ISSUE THREAD

**Issue by Thenewchicken55** [shaked6540/YoutubePlaylistDownloader#271]
Edge and Windows flag the installer as if it's malware saying "couldn't verify the source...make sure you trust the source..." I know you can bypass this, but it's just slightly suspicious that this happens. Maybe because there isn't a publisher. Not sure. Makes me (and others like me) second guess trusting this software lol even though I know it's probably safe.
![image](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/97483512/4eaa4429-e76f-4c63-82eb-94cc3c0af703)
![image](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/97483512/05082c8c-b2d9-49c6-a5fe-58d640636f23)

**Comment by shaked6540** [comment]
I honestly don't know how to solve something like that
There is nothing suspicious or malicious in the program, you can look at the source code
According to github, there have been 243,000 downloads of the program so far

**Comment by Thenewchicken55** [comment]
I understand. I don't actually believe it's malicious. But I think it has to do with the part saying "Publisher: Unknown" that's making it think it's risky. I'm not sure how to solve it either, just thought I should let you know. Feel free to close this issue. 

P.S. Thank you for this repo by the way. It's an amazing tool. Someday I'll try to make time to help out with development.

**Comment by shaked6540** [comment]
Thanks, it will be appreciated if you do help out in the future :)

**Comment by Thenewchicken55** [comment]
I know it's been 2 years haha. but I come across this tool that provides free code signing for open source code, if you haven't already figured it out https://signpath.io/

**Comment by shaked6540** [comment]
No thanks, it just complicates the entire process :) 
The source code is available for free for everyone, and today with AIs you can just ask it to check it for you if you don't have the time to check it yourself

**Comment by shaked6540** [comment]
Also the signing is not free or open source, otherwise malware could sign themselves too and it would become pointless
