### ISSUE TITLE
Unsure how to make the name ONLY the title of the song

### ISSUE THREAD

**Issue by seriousgamer42** [shaked6540/YoutubePlaylistDownloader#272]
I am unsure to to make the name of the file ONLY the title of the song.
What I am receiving is 'artist - title', how do I make it only the title?

**Comment by shaked6540** [comment]
If you go to Help -> File name pattern you can see all the available variables for the file name pattern. In your case, you should use "$artist - $songtitle"
![image](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/13851815/bb259061-f323-4b8b-af60-edf1a103f4db)

**Comment by seriousgamer42** [comment]
Thanks
