### ISSUE TITLE
"The drive or UNC share you selected does not exist or is not accessible. Please select another."

### ISSUE THREAD

**Issue by matyisczech** [shaked6540/YoutubePlaylistDownloader#274]
Got this error while downloading the newest version in the setup, I have no idea what it means. any suggestions? thx for help

**Comment by shaked6540** [comment]
I honestly have no idea what this error is, when searching for it on the web most results suggest to try to remove the program using the control panel, so you could try that.

**Comment by matyisczech** [comment]
Thanks. I thought I already uninstalled the old version but when I looked into the programs in control panel it was still there. After uninstalling it correctly now, the installation worked just fine.
