### ISSUE TITLE
Author Supports Genocide

### ISSUE THREAD

**Issue by thymetime** [shaked6540/YoutubePlaylistDownloader#282]
"Stand with Israel" on the readme. The nation of Israel is currently committing a genocide against Palestine, bombing hospitals, schools, and aid facilities. Seems like a pretty big issue to me.

**Comment by shaked6540** [comment]
You're right, please donate to fuck the IDF (fidf) so you can help fuck the IDF at this link: https://support.fidf.org/site/Donation2?df_id=1647&mfc_pref=T&1647.donation=form1&s_src=ORG_FIDF_HP_20240102_GlobalHeader&s_subsrc=2024_HP_FIDFHQNational_GlobalHeader-Donate

**Comment by Solo4working** [comment]
> 你是对的，请向以色列国防军（fidf）捐款，这样你就可以通过此链接帮助以色列国防军：[https://support.fidf.org/site/Donation2 ?df_id=1647&mfc_pref=T&1647.donation=form1&s_src=ORG_FIDF_HP_20240102_GlobalHeader&s_subsrc=2024_HP_FIDFHQNational_GlobalHeader-Donate](https://support.fidf.org/site/Donation2?df_id=1647&mfc_pref=T&1647.donation=form1&s_src=ORG_FIDF_HP_20240102_GlobalHeader&s_subsrc=2024_HP_FIDFHQNational_GlobalHeader-Donate)

shame on you, the genocide

**Comment by shaked6540** [comment]
> > 你是对的，请向以色列国防军（fidf）捐款，这样你就可以通过此链接帮助以色列国防军：[https://support.fidf.org/site/Donation2 ?df_id=1647&mfc_pref=T&1647.donation=form1&s_src=ORG_FIDF_HP_20240102_GlobalHeader&s_subsrc=2024_HP_FIDFHQNational_GlobalHeader-Donate](https://support.fidf.org/site/Donation2?df_id=1647&mfc_pref=T&1647.donation=form1&s_src=ORG_FIDF_HP_20240102_GlobalHeader&s_subsrc=2024_HP_FIDFHQNational_GlobalHeader-Donate)
> 
> shame on you, the genocide

Maybe you should visit a certain square in Beijing, of the Tiananmen kind. I wonder how many students were there at, say, 1989. 
And how many thousands were killed. 
Shame on you, the genocide
