### ISSUE TITLE
REQUEST: Add option to FILTER what it downloads

### ISSUE THREAD

**Issue by heyvoon** [shaked6540/YoutubePlaylistDownloader#29]
Hi and first of all thank you for this great peace of software. Awesome job.

Do you think would be viable to add options to filter what it downloads from the playlists?

Ex.: I don't want to download DJ Sets and stuff. I would like to download only single songs. Would be nice to have an option to filter. Like don't download anything above 20min or something like that.

Thank you in advance ;-) Keep up the great work!

**Comment by shaked6540** [comment]
That's a bit vague, I was planning to add an option to individually pick videos you don't want to download, but this feature didn't play nice with large playlists so I didn't add it in the end. I might find a solution to that problem since I have some time now. 

Would that be what you're looking for?

**Comment by heyvoon** [comment]
"option to individually pick videos" This is also nice. Similar to what I've requested. 
I use your app to download playlists from ytube so I can make mixtapes djing. Sometimes those playlists have unwanted stuff. Specially these large music videos over 1hr. Woulb be nice to filter these out. If you could implement the YouTube's filers itself would do it.

![image](https://user-images.githubusercontent.com/3281265/81287590-50347a80-9063-11ea-9e34-9b3da43bcd68.png)

Another workaround I found but is very time consuming is to create a Playlist of my own and download that one. 
But definitely would be very handy to just exclude by filtering. ;-) 

Thanks again man and be safe ;-)

**Comment by shaked6540** [comment]
> when downloading music from ytube. What is the maximum kbps it download it before it compress?

**Usually** youtube doesn't store anything over 138kbps in opus format, there are some cases they might decide to go beyond 138kbps, and sometimes they even go below that

I'll start working on the filtering soon

**Comment by shaked6540** [comment]
I added the filtering you requested, let me know if you're still missing some features

**Comment by heyvoon** [comment]
> I added the filtering you requested, let me know if you're still missing some features

Wow! That was fast! Very very sweet. One more thing! Remember to also add this filter option on the subscription settings;

![image](https://user-images.githubusercontent.com/3281265/81535730-9b53d380-936a-11ea-9c8f-df5e943dc734.png)

Cheers mate.

**Comment by shaked6540** [comment]
I completely forgot about that, it has been added
