### ISSUE TITLE
I can't download playlist as mp3

### ISSUE THREAD

**Issue by BaydoganMirac** [shaked6540/YoutubePlaylistDownloader#295]
Hello, I can't download playlist as mp3. I can download only mp4 or mkv. Can you help me?

Settings; 
![YoutubeDownloadSS](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/44525852/30a27333-5dc2-432c-b15c-fc7f42966243)

**Comment by cristianst85** [comment]
If I remember correctly you need to uncheck `Download clean audio, without converting to any format`.

**Comment by BaydoganMirac** [comment]
Its works, thank you <3
