### ISSUE TITLE
REQUEST: Add "Update Now" Button to subscriptions page.

### ISSUE THREAD

**Issue by heyvoon** [shaked6540/YoutubePlaylistDownloader#30]
Hi Mate,

Thank you again for your nice work. Hopefully your app is useful to other as it has been to me. Can emphasize that enough. 

Add "Update Now" Button to subscriptions page.

![image](https://user-images.githubusercontent.com/3281265/82062619-aab88100-96ca-11ea-9a7a-43724a747ea3.png)
 
**Taking advantage here on this request and asking if you could also add another filter like the one you added. So we could choose to download < and >.  ;-)**

**Comment by shaked6540** [comment]
I will try to add this soon, got a bit of work right now but I will have time to add it this week

**Comment by shaked6540** [comment]
Since subscriptions are no longer possible due to YouTube changes, I am closing this
Sorry I didn't get to implement it after all
