### ISSUE TITLE
Videos are converting to webm instead of mp3

### ISSUE THREAD

**Issue by DarrenChung2** [shaked6540/YoutubePlaylistDownloader#300]
despite the setting of converting videos to mp3 being on it still converts to webm, and am not sure why.

**Comment by shaked6540** [comment]
You probably have "Download clean audio, without converting to any format" turned on, disable this setting and it should be converted to mp3: 
![image](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/13851815/b6296d1c-adea-4c5f-897f-890a9d6ae745)

**Comment by DarrenChung2** [comment]
Thanks, that fixed the issue!
