### ISSUE TITLE
It's possbile to save the video miniature/picture?

### ISSUE THREAD

**Issue by dardizzola** [shaked6540/YoutubePlaylistDownloader#305]

**Comment by shaked6540** [comment]
Yes, but you don't need the program to do that, just go to: https://img.youtube.com/vi/{video Id}/maxresdefault.jpg

The video id is the last part of the url of a youtube video, after the "v=" for example, for this video: https://www.youtube.com/watch?v=DJONf_d3V0Q

The id is "DJONf_d3V0Q"

So to get the picture of it, you need to go to https://img.youtube.com/vi/DJONf_d3V0Q/maxresdefault.jpg

**Comment by dardizzola** [comment]
Yes, ok. But i need tonsave it as the same way te software save save the video and the srt.Would be very useful that it will save the description.Inviato da mobileIl giorno 13 lug 2024, alle ore 16:07, Shaked Dahan ***@***.***> ha scritto:﻿
Yes, but you don't need the program to do that, just go to: https://img.youtube.com/vi/{video Id}/maxresdefault.jpg
The video id is the last part of the url of a youtube video, after the "v=" for example, for this video: https://www.youtube.com/watch?v=DJONf_d3V0Q
The id is "DJONf_d3V0Q"
So to get the picture of it, you need to go to https://img.youtube.com/vi/DJONf_d3V0Q/maxresdefault.jpg

**Comment by shaked6540** [comment]
Currently there is no option to do that in the program

**Comment by dardizzola** [comment]
Could be implemented?Inviato da mobileIl giorno 13 lug 2024, alle ore 19:12, Shaked Dahan ***@***.***> ha scritto:﻿
Currently there is no option to do that in the program

**Comment by shaked6540** [comment]
Not for you, thief
