### ISSUE TITLE
REQUEST: Bulk tab does not have any options

### ISSUE THREAD

**Issue by heyvoon** [shaked6540/YoutubePlaylistDownloader#31]
Hi mate. Hope you are doing well on this lockdown shit. I found that the Bulk tab does not have any options.

![image](https://user-images.githubusercontent.com/3281265/82073477-98920f00-96d9-11ea-99c8-d23a9ffc0737.png)

**Comment by shaked6540** [comment]
The settings used in the Search tab are used in the bulk download as well

**Comment by heyvoon** [comment]
Awesome. Close this one than. Thanks
