### ISSUE TITLE
Romanian translation

### ISSUE THREAD

**Issue by deeaeu** [shaked6540/YoutubePlaylistDownloader#310]
I have translated the English.xaml in Romanian and would like to give it to you

**Comment by cristianst85** [comment]
Make a pull request so that I can review it.

**Comment by shaked6540** [comment]
If you dont know how to make pull request you can also send it here (drag and drop the file here) and I'll merge it for you

**Comment by deeaeu** [comment]
[Română.txt](https://github.com/user-attachments/files/16322578/Romana.txt)
it seems i can't send it as .xaml so i sent it as .txt

**Comment by deeaeu** [comment]
Sadly I am extremely inexperienced with GitHub so creating a pull request is a bit too much for me, thank you for understanding!
