### ISSUE TITLE
Make one which is cross-platform for Linux and mac

### ISSUE THREAD

**Issue by tmjoris** [shaked6540/YoutubePlaylistDownloader#311]
The current one is only usable on Windows. Can you add one for Linux and Mac, or make one which is cross-platform?

**Comment by shaked6540** [comment]
Sorry, can't do that currently. No plans to support Linux or Mac. 
The project is based on WPF by microsoft, which is windows only. To make a Linux or Mac version I'll have to write everything from scratch and I don't have time for that right now
