### ISSUE TITLE
Redesign of the navigation bar

### ISSUE THREAD

**Issue by Korb** [shaked6540/YoutubePlaylistDownloader#316]
The navigation area now looks like this:
![2024-07-30_14-03-42](https://github.com/user-attachments/assets/b243a0f9-8601-4e26-9323-6041c0206abe)
![2024-07-30_14-04-09](https://github.com/user-attachments/assets/0780cdbb-bb34-4da6-9a53-2196b9f446fd)
![2024-07-30_14-03-55](https://github.com/user-attachments/assets/f42a9f0b-7e24-4af0-817e-0dee68898d66)
![2024-07-30_14-04-22](https://github.com/user-attachments/assets/724f5d98-039e-4ea5-8e0d-495746dfda0a)
![2024-07-30_14-04-16](https://github.com/user-attachments/assets/d811d916-7291-4bca-b21e-20b7a7ef840e)

Agree, the buttons behave somewhat chaotically.

I suggest replacing it with tabs, or using a panel where each item will always be in the same place, but one of them will always be pressed or highlighted (depending on which was selected last / which screen is currently displayed).

![2024-07-31_13-45-48](https://github.com/user-attachments/assets/8330929f-0fa5-4944-a45e-e602e98be5ff)

**Comment by shaked6540** [comment]
Thanks for the suggestion, but I like it the way it is now, i made it like that on purpose
