### ISSUE TITLE
REQUEST: Download from YouTube query.

### ISSUE THREAD

**Issue by heyvoon** [shaked6540/YoutubePlaylistDownloader#32]
Me again ;-)

Could you add an option to download from a YouTube query?

https://www.youtube.com/results?search_query=SOMETHIG+DOWNLOAD

This would be awesome! RIght now the App will not recognize this type of URL.

![image](https://user-images.githubusercontent.com/3281265/82073993-5c12e300-96da-11ea-8d4d-4ed90d2a319c.png)

**Comment by shaked6540** [comment]
What would it download? all the results or just the first one? I don't think I will add this because its confusing

**Comment by heyvoon** [comment]
It would download ALL results from a search. And you could use filters like the one you did before to filter out he results. But this would be awesome. 
At this moment your app DOES allow to download a whole channel and YT topics. But not serach result.

**Comment by shaked6540** [comment]
I thought about it for a bit and I think that this feature isn't very useful for everyone, if you search for something you will most likely get the same video, just from different up-loaders. 

Do you need it yourself, or are you just trying to think of ideas to improve my program?

**Comment by heyvoon** [comment]
> I thought about it for a bit and I think that this feature isn't very useful for everyone, if you search for something you will most likely get the same video, just from different up-loaders.

Yep. You are right mate. Definitely thinking of improving. But what u said also make sense.
