### ISSUE TITLE
Uniform appearance and location of the "Back" ("Home") button

### ISSUE THREAD

**Issue by Korb** [shaked6540/YoutubePlaylistDownloader#321]
In the current version of the application, this button on different screens of the application looks like this:

![2024-07-30_18-24-41](https://github.com/user-attachments/assets/277678dd-4d7f-4780-82a5-2687ab7f7599)
![2024-07-30_18-24-48](https://github.com/user-attachments/assets/a03a741f-d269-470f-8fc9-b822cd93597e)
![2024-07-30_18-24-54](https://github.com/user-attachments/assets/a1a623bb-dba7-4b50-8eab-b9cdbe622143)
![2024-07-30_18-25-01](https://github.com/user-attachments/assets/8af99225-7cc1-4e51-b6f9-ac2a0c660eaa)

I suggest choosing the design that best matches the rest of the controls and sticking with it, fixing the buttons that don't match.

**Comment by shaked6540** [comment]
I don't get what the problem is, in any case I dont want to change how it works right now
