### ISSUE TITLE
Remember current session for next launch

### ISSUE THREAD

**Issue by Korb** [shaked6540/YoutubePlaylistDownloader#324]
If the application does not support resuming downloads after interruption, then at least consider saving the contents of the Queue tab. Ideally, session snapshot should be performed at a user-specified frequency.

In YouTube Playlist Downloader 1.924, after restarting the application, only the application settings are saved, but not the download history, including their statuses.

**Comment by shaked6540** [comment]
This is outside the scope of the program. Its meant to download youtube playlists, its not a download manager
