### ISSUE TITLE
REQUEST: RESUME where i left off and not redownload everything

### ISSUE THREAD

**Issue by heyvoon** [shaked6540/YoutubePlaylistDownloader#33]
Right now your when downloading a playlist. If the software crashes or something and you try to download again it will replace and reprocess all the files on the same folder. It would be nice if it could detect existing files and skip.

**Comment by shaked6540** [comment]
I've got a bit of work on my hands right now so I won't be adding any new features or updates any time soon, sorry. 

The only updates will be bug fixes, in case YouTube changes something and the program stops working completely

I'll keep this issue open and maybe get back to it in the future. 

By the way, if the program crashed while downloading please report it to me, tell me what you did and what happened and if its something small I will fix it right away

**Comment by NeeZaaR** [comment]
this issue still remaining which if there 30 videos downloading and already 15 video's downloaded then PC shut downed due updates then if you trying to continue the remaining then will start again to download 30 video's not 15 video's which are remaining. you have to consider that in your plan
