### ISSUE TITLE
Can't start download

### ISSUE THREAD

**Issue by MihailF4** [shaked6540/YoutubePlaylistDownloader#336]
Hello,
 I just put the playlist link and the download link doesn't work, until now it did worked.
![image_2024-08-22_113838135](https://github.com/user-attachments/assets/1252326a-cdcc-4376-8125-6a7659824875)
It's the same thing I did when I first downloaded the app. I have a output folder*

**Comment by shaked6540** [comment]
make sure the playlist is public or unlisted

**Comment by MihailF4** [comment]
That works, thanks!
