### ISSUE TITLE
Facing error "Reason: Object reference not set to an instance of an object." when downloading video using bulk download.

### ISSUE THREAD

**Issue by cyruslei0501** [shaked6540/YoutubePlaylistDownloader#337]
As title wrote, the error pop up when I tried to **download and convert from video to audio** in "Bulk Download" mode.
I paste the links in the big text box like:
https://www.youtube.com/watch?v=NbgDOtxhvZk
https://www.youtube.com/watch?v=Bx7k5R0taFk
https://www.youtube.com/watch?v=DdB-_OqWUrE
https://www.youtube.com/watch?v=xfiZlbrbHMQ
https://www.youtube.com/watch?v=FAefubqNXUI
https://www.youtube.com/watch?v=cDb51CHu3ng
https://www.youtube.com/watch?v=V7Mkgiik_M0
https://www.youtube.com/watch?v=dprPJGYdJ8s
https://www.youtube.com/watch?v=hjbcc7GC_o8
https://www.youtube.com/watch?v=4jit_SPagrI
...and 926 more links.

If I'm not converting from video to audio, everything's fine.
The huge amount of links probably not the cause of this error because I tried putting just one link and press Download but it still not working.
Can anyone help me out :(((( love lofi music

**Comment by shaked6540** [comment]
Hey, there is currently a bug in the bulk download section, unfortunately I don't have time to solve it now, I will be free in 1 month and I will fix a lot of bugs then. Until then, you'll need to find another solution :( 
You can try yt-dlp if you're familiar with the command line

**Comment by cyruslei0501** [comment]
Thanks for your reply! Sure~ I'll try out yt-dlp. Also thanks for making this wonderful downloader :D

**Comment by Jeedai** [comment]
Did you fix it?

**Comment by shaked6540** [comment]
Should be solved in the latest update (1.9.25)
