### ISSUE TITLE
Why TagLibSharp is not installed from NuGet?

### ISSUE THREAD

**Issue by cristianst85** [shaked6540/YoutubePlaylistDownloader#34]
Hi,

Is there any reason why TagLibSharp 2.2.0 is not installed from NuGet?

Local TagLibSharp.dll SHA-1: 9A8DB8B9EC116A6C103FF8E03C0D50B3711E1C0F (size: 481 KB (493.056 bytes))
NuGet TagLibSharp.dll SHA-1: 76F35D7DE9ACBDB8B3FC11147741D4FA37983919 (size: 480 KB (492.032 bytes))

P.S. I can submit a PR if you want to address this.

Thank you!

**Comment by shaked6540** [comment]
When I first made this program I don't think TagLibSharp was on nuget, you could make a PR, but make sure to test the tagging capabilities before you submit it
