### ISSUE TITLE
Downloader No longer Functional

### ISSUE THREAD

**Issue by TyrDr0p** [shaked6540/YoutubePlaylistDownloader#340]
Youtube is flagging the program as a bot making downloads not possible

Here is a list of the videos that could not be downloaded, and the reason why: 
Theme From Killer Klowns From Outer Space (2018 Recording) Reason: Video 'LdvyGSwrysY' is unplayable. Reason: 'Sign in to confirm you’re not a bot'.

**Comment by shaked6540** [comment]
Nothing I can do about it, sorry

**Comment by TyrDr0p** [comment]
Understood. So sad to see a good tool die.
