### ISSUE TITLE
"Video watch page is broken. Please try again in a few minutes."

### ISSUE THREAD

**Issue by Borists1** [shaked6540/YoutubePlaylistDownloader#345]
Since today, whenever i try to download a video, it displays the error "Video watch page is broken. Please try again in a few minutes.". (the error can be gotten when downloading in bulk)

**Comment by Borists1** [comment]
It seems to only affect single videos, not playlists

**Comment by shaked6540** [comment]
I'll check this out when I have time, if by any chance it gets fixed by itself let me know

**Comment by HWH53** [comment]
> Since today, whenever i try to download a video, it displays the error "Video watch page is broken. Please try again in a few minutes.". (the error can be gotten when downloading in bulk)

Same Problem here.
Raspberry Pi Pico W LESSON 87: Introduction to Raspberry Pi Pico PIO and State Machines
https://www.youtube.com/watch?v=PXE7q25Mf1E&t=1s 
What they have changed at YouTube?😆

**Comment by shaked6540** [comment]
Should be solved in the latest update (1.9.25)
