### ISSUE TITLE
Bulk Download error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Jeedai** [shaked6540/YoutubePlaylistDownloader#349]
I was trying to download these tracks and this error.
Thank you for your help.

Here is a list of the videos that could not be downloaded, and the reason why: 
https://www.youtube.com/watch?v=Zoaxsq4qqgI Reason: Object reference not set to an instance of an object.
https://www.youtube.com/watch?v=7Ct1GIzjkok Reason: Object reference not set to an instance of an object.
https://www.youtube.com/watch?v=uXaKRM5y2U8 Reason: Object reference not set to an instance of an object.
https://www.youtube.com/watch?v=BIGjHuHCcRM Reason: Object reference not set to an instance of an object.
https://www.youtube.com/watch?v=213RH_AfucU Reason: Object reference not set to an instance of an object.
https://www.youtube.com/watch?v=KhktXWzMHKU Reason: Object reference not set to an instance of an object.
https://www.youtube.com/watch?v=UOEaZOHyo6w Reason: Object reference not set to an instance of an object

**Comment by shaked6540** [comment]
Should be solved in the latest update (1.9.25)

**Comment by Jeedai** [comment]
Thank you!
