### ISSUE TITLE
after downloading 100% of the video, there is nowhere

### ISSUE THREAD

**Issue by BogdanBTO** [shaked6540/YoutubePlaylistDownloader#352]
after downloading and going to the folder with the video, it turns out to be empty, there may be some conflict with Cyrillic, I have a weight in Russian, maybe the program does not know how to work with it.

**Comment by shaked6540** [comment]
There is no problem with Cyrillic, try running the program as administrator and see if it works

**Comment by BogdanBTO** [comment]
oh, thanks, I just had to wait longer, I thought it worked much faster, but I like that it's open source and written in c sharp.
