### ISSUE TITLE
Response status code does not indicate success: 403 (Forbidden) appears for every video. 

### ISSUE THREAD

**Issue by HorizonOfek** [shaked6540/YoutubePlaylistDownloader#354]
Downloading no longer functions and always shows the error message "Response status code does not indicate success: 403 (Forbidden)".

**Comment by MayBeDav** [comment]
Same here. Seems like a universal issue. Hope it gets fixed soon.

**Comment by phoenix529** [comment]
Same problem

**Comment by ChromusMaster** [comment]
Same here

**Comment by GriimSoul** [comment]
Same here, thought it was just my PC, since I recently reinstalled Windows.
Both glad and sad it wasn't the case.

**Comment by Tech1207** [comment]
Same also

**Comment by SaltySnacky** [comment]
Same for me aswell

**Comment by TiedEnd** [comment]
same for me

**Comment by Nellaimuthuvel** [comment]
Same for me

**Comment by colt4567** [comment]
Same for me.
Can't video is downloade. error 403  every videos.
Please update.

**Comment by shaked6540** [comment]
Hey, I'm aware of the issue and working on a fix. I dont know how long it will take because I'm under fire from Hezbollah, I hope to finish it by next week. In the meantime, if anyone wants to make a PR to solve it - go ahead.

**Comment by nazmul-nhb** [comment]
having the same issue

**Comment by Dumbynaut** [comment]
> Hey, I'm aware of the issue and working on a fix. I dont know how long it will take because I'm under fire from Hezbollah, I hope to finish it by next week. In the meantime, if anyone wants to make a PR to solve it - go ahead.

Stay safe and take your time, brother.

**Comment by alexanderpowerplays** [comment]
im having the same error

pretty sure youtube decided to stop us from downloading stuff and so it throws up a 403 error

**Comment by na791** [comment]
any idea on whether it will be possible to fix it?

**Comment by dbrewerton** [comment]
Got the same issue.

**Comment by dani31c** [comment]
@shaked6540 I dont know if this has been reported too, but there is also another error, which is something around these lines:
verify that you are not a robot

**Comment by Neimod2004** [comment]
Same problem, I am using cli yt-dlp, but it is a lot slower because I can't use a queue

**Comment by Kamwebdev** [comment]
> Yes, everyone has the same issue. Apparently updating `YoutubeExplode` library to the latest version (6.4.2) fixes this issue.

It works! Thanks!

Steps to build own fixed copy:
1. I clone fully repository to C:\Users\my_username\Downloads\YoutubePlaylistDownloader
2. Manual apply [commit](https://github.com/cristianst85/YoutubePlaylistDownloader/commit/8a36cb76f475d028ec1ded41281e8f7412fa6e05). 
3. After that i copy 
from: C:\Program Files (x86)\YouTube Playlist Downloader\ffmpeg.exe  
to:" C:\Users\my_username\Downloads\YoutubePlaylistDownloader\YoutubePlaylistDownloader\bin\Debug\net8.0-windows\ffmpeg.exe
4. The last step was build package (only open YoutubePlaylistDownloader.sln by JetbrainsRider  and click run).

**Comment by colt4567** [comment]
Thank you very much.
It work.

Update YoutubeExplode.dll 6.4.2.

**Comment by Neimod2004** [comment]
Thank you so much for the solution

**Comment by MonsieurOrnix** [comment]
Thank you very much. After an update of the NuGet package YoutubeExplode, it works for me too.
תודה רבה
שתהיה שנה יותר טובה

**Comment by JPCAlencar** [comment]
How are you doing, guys? Can anyone help me real quick?
Where do I find where to commit? I browsed through YoutubeExplode.dll in Notepad, but it's in binary. I couldn't find where to make the change. Do I have to do it in YoutubeExplode.dll or in another file? I'm kinda lost hahaha

**Comment by MonsieurOrnix** [comment]
In YoutubePlaylistDownloader.csproj, line 78.

**Comment by MonsieurOrnix** [comment]
@JPCAlencar In YoutubePlaylistDownloader.csproj, line 78.
Or this command in the project folder : `dotnet add package YoutubeExplode --version 6.4.3`

**Comment by JPCAlencar** [comment]
@MonsieurOrnix ok, i will try here and i comeback to tell if i figured out

**Comment by JPCAlencar** [comment]
@MonsieurOrnix Man, I went to the YoutubePlaylistDownloader folder and didn’t find the 'YoutubePlaylistDownloader.csproj' file. I’m not sure if I installed it wrong or if it didn’t come. Where can I find the .csproj? Is it in a subfolder?

**Comment by Kamwebdev** [comment]
> @MonsieurOrnix Man, I went to the YoutubePlaylistDownloader folder and didn’t find the 'YoutubePlaylistDownloader.csproj' file. I’m not sure if I installed it wrong or if it didn’t come. Where can I find the .csproj? Is it in a subfolder?

After run "git clone https://github.com/shaked6540/YoutubePlaylistDownloader"
You will find file in YoutubePlaylistDownloader/YoutubePlaylistDownloader.csproj

**Comment by MonsieurOrnix** [comment]
@JPCAlencar Did you clone the repository ? If not, there's a simple solution : download the package [here](https://www.nuget.org/packages/YoutubeExplode). Change the .nupkg extension to .zip in order to unzip the file. In /lib/net8.0, you'll find the YoutubeExplode.dll file you need to copy in order to replace the old one (in C:\Program Files (x86)\YouTube Playlist Downloader).

**Comment by JPCAlencar** [comment]
@MonsieurOrnix Thanks, man! You’re a G.O.A.T. I’ve been trying to make this work all day, and you helped me 100%. I really appreciate it! Have a good one!

**Comment by msarun77** [comment]
> @JPCAlencar Did you clone the repository ? If not, there's a simple solution : download the package [here](https://www.nuget.org/packages/YoutubeExplode). Change the .nupkg extension to .zip in order to unzip the file. In /lib/net8.0, you'll find the YoutubeExplode.dll file you need to copy in order to replace the old one (in C:\Program Files (x86)\YouTube Playlist Downloader).

Thank you. It worked.

**Comment by msarun77** [comment]
@MonsieurOrnix Thank you. It worked.

**Comment by shaked6540** [comment]
Should be solved in the latest update (1.9.25)

**Comment by dbrewerton** [comment]
Great work, it's working beautifully now. Confirmed fix.

**Comment by alexanderpowerplays** [comment]
is there a simpler way to apply this fix?

**Comment by Neimod2004** [comment]
@alexanderpowerplays if you update to the latest version it should be solved

**Comment by alexanderpowerplays** [comment]
i can try
