### ISSUE TITLE
Getting a 403 Error whenever i try to download songs....

### ISSUE THREAD

**Issue by Eliteben** [shaked6540/YoutubePlaylistDownloader#359]
I've tried over 20 different videos and none of them seem to work. Here is the error I'm getting:

Here is a list of the videos that could not be downloaded, and the reason why: 
Ed Sheeran - Shape of You (Official Music Video) Reason: Response status code does not indicate success: 403 (Forbidden).

**Comment by Alireza-F-kenedy** [comment]
Yep, same thing happened to me. I tried installing the program twice on two different computers, but it didn't fix it

**Comment by fat-sycophant** [comment]
me too

**Comment by TheOneTruth1611** [comment]
Same here

**Comment by cristianst85** [comment]
Duplicate of #354.

**Comment by shaked6540** [comment]
Should be solved in the latest update (1.9.25)
