### ISSUE TITLE
Playlist link will not work

### ISSUE THREAD

**Issue by PJBoogie** [shaked6540/YoutubePlaylistDownloader#364]
I paste the link into the space for bulk download, but nothing will come up in the queue. I don't understand, here's the link. Can you tell me what's wrong with it? Thank you!

https://www.youtube.com/playlist?list=PLw8AM0LVcN7g4goEaqoz06KI89fDq6_VT

**Comment by cristianst85** [comment]
Possible a duplicate of https://github.com/shaked6540/YoutubePlaylistDownloader/issues/354.

**Comment by shaked6540** [comment]
Should be solved in the latest update (1.9.25)

**Comment by PJBoogie** [comment]
Ok, thank you.
