### ISSUE TITLE
Can't download any more playlist

### ISSUE THREAD

**Issue by M0hamed-Eid** [shaked6540/YoutubePlaylistDownloader#365]
The following is the copy of clipboard and it says some but actually all of videos in playlist couldn't be downloaded and tried another playlist but same happens
Here is a list of the videos that could not be downloaded, and the reason why: 
1- شرح منهج السالكين للسعدي/الدرس الأول/الشيخ عثمان الخميس Reason: Response status code does not indicate success: 403 (Forbidden).
2- شرح منهج السالكين للسعدي/الدرس الثاني/الشيخ عثمان الخميس Reason: Response status code does not indicate success: 403 (Forbidden).
3- شرح منهج السالكين للسعدي/ الدرس الثالث/ الشيخ عثمان الخميس Reason: Response status code does not indicate success: 403 (Forbidden).
4  شرح منهج السالكين للسعدي/الدرس الرابع/الشيخ عثمان الخميس Reason: Response status code does not indicate success: 403 (Forbidden).
5  شرح منهج السالكين للسعدي/الدرس الخامس/الشيخ عثمان الخميس Reason: Response status code does not indicate success: 403 (Forbidden).

**Comment by shaked6540** [comment]
Should be solved in the latest update (1.9.25)
