### ISSUE TITLE
Israel is committing a genocide against the Palestinians

### ISSUE THREAD

**Issue by ctrlwhywhy** [shaked6540/YoutubePlaylistDownloader#371]
its not anti semetic to think this is wrong
its just wrong
fuck you and your whole project
i hope it burns to the ground

**Comment by shaked6540** [comment]
Its a digital project, it can't burn. All you know is murder and violence. 
80% of the people killed in Gaza are Hamas, and that's less than 1% of the population. Probably the worst genocide in the entire history of humanity.

**Comment by saphiratphantom** [comment]
That's a nice argument, why don't you back it up with a source?
