### ISSUE TITLE
Visually obvious choice of what to download

### ISSUE THREAD

**Issue by Korb** [shaked6540/YoutubePlaylistDownloader#384]
I suggest considering changing the interface to solve the problem of some settings not being obvious. Namely, what exactly needs to be downloaded.

As I understand it, [yt-dlp](https://github.com/yt-dlp/yt-dlp) basically allows you to download the video itself, audio, subtitles, description and cover. Each content type has its own settings, some types can be represented by more than one object (different resolutions and video formats, different bitrates and audio formats, different subtitle languages). That is, logically, the GUI-settings should represent four levels:

1. selecting content types to download;
2. selecting objects of the selected types (and only them, other types should be unavailable)
3. selecting the saving method (separate or gluing)
4. selecting the gluing format (available only if gluing is selected in the previous paragraph)

I do not suggest using the wizard. It seems to me that it is better to implement this on one page, as it is now. Or make it look like the foobar2000 converter:

![2024-10-17_09-49-21](https://github.com/user-attachments/assets/4cd6cf3d-c18c-4038-8d04-4e22cd24e6b9)

Replace `Output format` with `What to download`, `Destination` with `Select languages, resolutions, etc.`, `Processing` with `Separate or merged?` and `Other` with `Save formats` and you'll get an idea of ​​what I mean.

These changes will make the interface more logical and remove some inconsistencies when, for example, the user can change download settings that are not applicable to the current download or the settings set. For example, they can set video formats with the `Download clean audio, without converting to any format` option checked (which should make all video settings unavailable). Or configure the processing of playlists even though the link is not to the playlist.

Related issues: #113 and #295.

**Comment by shaked6540** [comment]
Its outside the scope of the project. Its meant to be a quick "paste and download" type of thing, I dont want to overcomplicate things.
