### ISSUE TITLE
No sound when downloading

### ISSUE THREAD

**Issue by Gamer9090-Cyber** [shaked6540/YoutubePlaylistDownloader#387]
Hi, i downloaded your youtube playlist downloader, it's really good and really helpful. however i tried downloading videos today and the videos have no sound, like it didn't before but after downloading these videos, anything after had no sound. idk why, like idk if it's a copyright problem or something. i sure would like some help. It's specific videos too, like some videos work fine but i can't figure out why some vids have no sound

**Comment by shaked6540** [comment]
Do you use the built in media player in windows? It's outdated and doesn't support youtube's formats, try opening the files with VLC.

**Comment by Gamer9090-Cyber** [comment]
i'm not sure, i just download it through it and it's worked fine. it's specific videos only, i worked around it tho. i Just want to know why it affects specific videos. Idk if it's a bug cuz it works for some other downloaders so.

**Comment by Gamer9090-Cyber** [comment]
hi, i Downloaded and tried using VLC, all the videos that are silent, it works! Amazing thanks man!

**Comment by Gamer9090-Cyber** [comment]
also why can't this application download 18+ videos? like age restriction on youtube? it should cuz that's all this is missing

**Comment by shaked6540** [comment]
It's impossible to download age restricted videos without logging in, and I don't plan to support logging in. 
Glad your problem was sovled
