### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Zebre2007-2** [shaked6540/YoutubePlaylistDownloader#393]
Argh the French translation is so bad x)
I think it's better to make a team to translate and verify all translations.

There may be other translations of languages that are not good

In the help, the category "file name pattern" is not translated

**Comment by Zebre2007-2** [comment]
There may be other translations of languages that are not good

**Comment by shaked6540** [comment]
Hey, I don't know French, it was translated by a community member. Feel free to fix whatever you find problematic :)

**Comment by Zebre2007-2** [comment]
Do I change Elta by my name ?

`<s:String x:Key="CreditsAndContributors">Un grand merci à ces personnes pour la traduction de ce logiciel :
Dong Cunrui (董存瑞)
RichyZ99
Jhonatan Lima (Heremitus)
İskender ALPSAKARYA, Alp Eren GENÇOĞLU (Türkçe)
Stephan Komov (Deutsch)
Elta (Français)
Ahmed Waaer (Arabic)
Bartlomiej Szmolke (Polski)
Timofey Dedov (Русский)
deeaeu (Română)
</s:String>`

**Comment by cristianst85** [comment]
Do not change it. Just add your name after it. See Türkçe.
You may also update that line in the rest of the language files.

**Comment by Zebre2007-2** [comment]
Ok the french translation is ready. How can I publish it?

**Comment by cristianst85** [comment]
You need to create a pull request. If you don't know how to work with git and GitHub just attach the file here.

**Comment by Zebre2007-2** [comment]
[French Translation.zip](https://github.com/user-attachments/files/17450573/French.Translation.zip)

**Comment by cristianst85** [comment]
I forgot to mention this to you. Did you reckeck all translation strings? The English file may had suffered some changes/corrections over the time.

**Comment by Zebre2007-2** [comment]
I downloaded the zip of the code

**Comment by cristianst85** [comment]
What I am asking if you did check all the strings in the French file to be in sync with the English ones?

**Comment by Zebre2007-2** [comment]
yep

**Comment by cristianst85** [comment]
Is there a reason why you added spaces before `:` and `?`.

**Comment by Zebre2007-2** [comment]
In French, a space is always added before the punctuation ( `: , ! ?` ).
