### ISSUE TITLE
Non-Windows support

### ISSUE THREAD

**Issue by massblabla** [shaked6540/YoutubePlaylistDownloader#396]
I need this, but there is 1 important thing that made me say **No** to this project.  
  
1. **IT'S ONLY FOR MICROSOFT WINDOWS**
2. ~~that big fine print that says "Stand with Israel"~~ that's another problem

**Comment by shaked6540** [comment]
Are you serious? What makes you think I own you anything? The world doesn't revolve around you kid. Get out of here

**Comment by massblabla** [comment]
I knew that, putting this in my TODO list, thank you
