### ISSUE TITLE
cannot find the downloaded files

### ISSUE THREAD

**Issue by kayzeppl** [shaked6540/YoutubePlaylistDownloader#403]
hey, i cannot find the downloaded files, windows file search cant either.
the download itself seems to work.
i ran the program normally and as an administrator, and also tried switching the dl folder to a not-OS disk.
using win10.
any suggestions?
edit: other preferences are default, also tried to save as mp3 but that did not work either.
do ytmusic playlists work? it was a yt music link, https://music.youtube.com/playlist?list=OLAK5uy_mHkdHx8Ne03ql0Ou--0EzKPZdUjhOpFG4 to be more precise.
edit2: it worked when i switched users to admin, giving the app the rights did not suffice.

**Comment by shaked6540** [comment]
So you managed to solve it?

**Comment by cristianst85** [comment]
Make an effort to read the other similar issues and you'll find an answer to your question.
