### ISSUE TITLE
Time format issue

### ISSUE THREAD

**Issue by Elta305** [shaked6540/YoutubePlaylistDownloader#41]
The time format changes depending on the language of the pc and prevents the playlist from downloading. For the software to work you need the time format "yyyy-MM-dd" but other people can have the time format "dd / MM / yyyy" (this is the case in France). The format can be changed in the settings but this could cause problems for those who do not know this feature.

**Comment by shaked6540** [comment]
I'm not using time formats when downloading playlists, did you mean the 'Subscriptions' tab? 

I'm using the `dd/MM/yyyy` format myself and I don't have any issues with downloading playlists

**Comment by shaked6540** [comment]
Thats very strange, I'm able to download it, my system time format is dd/MM/yyyy. 
Do you get an error or is it just not downloading? could you share the Errors.txt file? it is located at `%appdata%\Youtube Playlist Downloader`

**Comment by Elta305** [comment]
"Le format de la chaîne d'entrée est incorrect." means "The format of the input string is incorrect." and "La clé donnée était absente du dictionnaire." means "The given key was missing from the dictionary." Idk why it's not in english in the file.

[Errors.txt](https://github.com/shaked6540/YoutubePlaylistDownloader/files/5304666/Errors.txt)

**Comment by Elta305** [comment]
I tried again and the download worked.

**Comment by shaked6540** [comment]
It could be something on YouTube's end, if it works now that's the only hypothesis I have
