### ISSUE TITLE
ISSUE: Cannot download the installer

### ISSUE THREAD

**Issue by sheharyaar** [shaked6540/YoutubePlaylistDownloader#42]
The Google Drive page says that the file is infected with virus and the owner only can download the file.
![image](https://user-images.githubusercontent.com/34273345/98673654-aae5c080-237d-11eb-90e6-1a74e9ed78e2.png)

**Comment by shaked6540** [comment]
that's strange, its been working until now. I'll try to upload it again, and don't worry, there aren't any viruses in it

**Comment by shaked6540** [comment]
Could you try now? let me know if it works

**Comment by sheharyaar** [comment]
Box Cloud is showing error - The link you're trying to access can't be used to share files. Please ask the file owner to provide you with a shared link instead.
![image](https://user-images.githubusercontent.com/34273345/98715341-04ff7980-23b0-11eb-8caf-629005ea4d4d.png)

**Comment by shaked6540** [comment]
how about now?

**Comment by sheharyaar** [comment]
Yeah it works!! Thanks
