### ISSUE TITLE
403 (Forbidden)

### ISSUE THREAD

**Issue by jujujuujuu** [shaked6540/YoutubePlaylistDownloader#437]
I get this error while trying to download **anything** using the 1.9.25 version, which used to work **perfectly** fine up until like 2 days ago. I don't know if I'm the only one facing this issue. Anyways, hope this is an easy fix and I wish you all a good day.

**Comment by shaked6540** [comment]
Hey, I just tried downloading a couple of videos and I don't get any error. Can you send a link that causes the 403 error?

**Comment by jujujuujuu** [comment]
> Hey, I just tried downloading a couple of videos and I don't get any error. Can you send a link that causes the 403 error?

It my be just my computer, but no link works for me. For example: https://youtu.be/FGBhQbmPwH8?si=HSxFj2DYxHR_9IQp

If you need any other information from my end, just ask. Thanks!

**Comment by shaked6540** [comment]
That link works for me. Maybe its something with your settings? Could also be that youtube banned your IP from downloading if you downloaded a lot lately

**Comment by jujujuujuu** [comment]
Oh. I've been downloading a lot in just some days, I'm guessing it's that. Forgive my ignorance, but could using a VPN or something similar fix the issue?

**Comment by shaked6540** [comment]
Yep, a vpn should fix it if its indeed youtube blocking your ip. If it still gives you 403, then its likely something else that's causing it

**Comment by jujujuujuu** [comment]
That fixed the issue, thank you a lot! The attention and patience you have is incredible
