### ISSUE TITLE
Translation Request

### ISSUE THREAD

**Issue by ah7255703** [shaked6540/YoutubePlaylistDownloader#45]
I can Translate Your Project To Arabic Language 

-  استطيع ترجمة مشروعك الى اللغة العربية مجانا

**Comment by ah7255703** [comment]
ok I am almost Done

**Comment by ah7255703** [comment]
Is There Any Way To Test The Program With Arabic ? 
I want To Make Test Because Arabic Is "Right To Left"

**Comment by ah7255703** [comment]
[العربية.zip](https://github.com/shaked6540/YoutubePlaylistDownloader/files/5875855/default.zip)

**Comment by shaked6540** [comment]
> 
> 
> Is There Any Way To Test The Program With Arabic ?
> I want To Make a Test Because Arabic Is "Right To Left"

Don't worry, I know about that, Hebrew is also right to left and its working fine :) There's a special setting for Right to left languages so it should be good. I will release an update shortly with your translation, thanks!

**Comment by shaked6540** [comment]
The update is now out, you should be able to see your translation! Thanks again :)
