### ISSUE TITLE
Video and audio for 1 item in playlist separated in 2 files

### ISSUE THREAD

**Issue by PeterKillerio** [shaked6540/YoutubePlaylistDownloader#46]
After installing downloader and trying it out not changing any settings except (changing video quality to 1080p and checking "open destination folder when done" option) I got two files for every item in playlist with the same name but the video file was of type "File" and audio file was MP4 as you can see in the picture bellow. Video can be openned in vlc and windows media player (but doesn't have any sound). As for me, I don't mind as much I can easily add audio track to the video and the timing is correct. Love the tool.
![issue](https://user-images.githubusercontent.com/30775179/106466589-d0292d00-649b-11eb-8416-e2e2dcb49ce4.png)

**Comment by shaked6540** [comment]
Very strange, can you tell me what video caused this? I tried with a random video and this problem did not occur

**Comment by PeterKillerio** [comment]
It was a school lecture, unlisted youtube video. But I tried it with some random playlist after your message with the same result. 
After that, I tried to restart the computer (it wasn't restarted after installing) and tried it again, now with desktop as a video save folder.
Now, video was with .mkv postfix (before there was none) but the audio file is missing on the desktop. So as before, I looked up the downloaded files in temp folder and there they was (audio and video in 2 seperated files, video is playable if openned through a media player software but has no postfix format in the name, audio file now has postfix .webm).

**Comment by shaked6540** [comment]
I tried again, and I also tried on an unlisted video and I can't reproduce the issue. Try again while running the program as administrator (right clik-> run as administrator)

You can also send me the errors file so I can check what went wrong, the error file is located at `%appdata%/Youtube Playlist Downloader`

**Comment by PeterKillerio** [comment]
Tried starting it as administrator with no luck. Here is the error file (copied after I tried running it as administrator 2.2.2021)
[Errors.txt](https://github.com/shaked6540/YoutubePlaylistDownloader/files/5911159/Errors.txt)

**Comment by shaked6540** [comment]
I'm not able to reproduce this error, can you give me the link of the video? does it happen with ALL videos you're trying? Does it happen with [this video](https://www.youtube.com/watch?v=miP21jnj3RU) as well?

**Comment by PeterKillerio** [comment]
Yes, with your video as well.

**Comment by shaked6540** [comment]
I'm really sorry but I cant find a reason to why its not working for you.. it could that ffmpeg crashes, but that seems impossible since ffmpeg is very reliable

:(

**Comment by PeterKillerio** [comment]
Okay, its resolved. I'm not sure from when the option was available but now I could change the audio track. 
I wasn't able to do that earlier because there was none. Now even the files from temp folder are gone.
So it works now but I have to manually change the audio track.

**Comment by shaked6540** [comment]
I don't really understand what you mean by audio track, did you mean the audio format (mp3, opus, wav, etc)?

**Comment by shaked6540** [comment]
Oh, if its something in a 3rd party program then that's out of the scope of my program

If you want to be sure you could check your files with MediaInfo or a similar software

**Comment by PeterKillerio** [comment]
![obrázok](https://user-images.githubusercontent.com/30775179/106646561-30000080-658e-11eb-9b6b-f6ffabefa28b.png)

**Comment by shaked6540** [comment]
Np, have fun :)
