### ISSUE TITLE
Can't download any playlists

### ISSUE THREAD

**Issue by Redflame18** [shaked6540/YoutubePlaylistDownloader#47]
After inserting a playlist link into the search bar, my download button is still gray, and I can't download it, I tried to download it using the Bulk download, also didn't work, tried with over 8 playlists, and nothing, I can download solo videos just fine....

**Comment by shaked6540** [comment]
Seems like its not just you, Youtube has changed something and now the playlist feature is broken :( 
I'll have to wait until the library im using to fetch the playlists resolves this issue. When they do I will of course release an update

**Comment by shaked6540** [comment]
Hi, I've released an update that should solve this issue. Let me know if it works now

**Comment by Redflame18** [comment]
YES!! Thank You, It did fix the problem!
