### ISSUE TITLE
Some Videos Could not be Downloaded

### ISSUE THREAD

**Issue by nice9uy** [shaked6540/YoutubePlaylistDownloader#50]
Hi...

I got error like this

![ssssssssss](https://user-images.githubusercontent.com/25494182/111299189-39e34c00-8682-11eb-98ec-26587204fbf9.PNG)

Can you fix it this issue with add new future to retrying download videos automaticly. 
So, we cannot download video manualy.

Thanks for your great app

**Comment by shaked6540** [comment]
Can you link the video\playlist that gives you this error?

**Comment by shaked6540** [comment]
Closing this because I didn't get a response for over a week and I can't replicate the issue
