### ISSUE TITLE
All the video not able to convert to MP3 , it converts to WEBM format 

### ISSUE THREAD

**Issue by lhanxin0** [shaked6540/YoutubePlaylistDownloader#60]
I have click on the convert to MP3, but I still get WEBM format after I download

**Comment by shaked6540** [comment]
can you send me the error.txt file, located at `%appdata%/Youtube Playlist Downloader` (copy and paste that to file explorer and it will take you directly to the folder) And also, what settings are you using (a screenshot would be best)?

**Comment by andyparis03** [comment]
Hi, I have the same problem as @lhanxin0 ... I select MP3 and bitrate but it download only webm format (no mp3)

**Comment by shaked6540** [comment]
> Hi, I have the same problem as @lhanxin0 ... I select MP3 and bitrate but it download only webm format (no mp3)


can you send me the error.txt file, located at %appdata%/Youtube Playlist Downloader (copy and paste that to file explorer and it will take you directly to the folder) And also, what settings are you using (a screenshot would be best)

**Comment by andyparis03** [comment]
Hi Dahan thanks for your reply,
now it works perfect! I realised that when "Download clean audio" is
flagged then only download video and not mp3.
Many thanks now it's a charm!
A

**Comment by shaked6540** [comment]
@lhanxin0 does this solve your issue as well?
