### ISSUE TITLE
downloader doesnt save to folder

### ISSUE THREAD

**Issue by vgc12** [shaked6540/YoutubePlaylistDownloader#66]
hey I tried downloading a playlist and it didn't download any of the songs, but when I closed it and reopened it it worked. its not that big of a deal but I'm posting this for anyone else who has this issue.

**Comment by shaked6540** [comment]
I can try investigating the issue if you give me the logs, usually when this happens it means the program doesn't have permissions to copy files to your destination folder

The log files are located at `%appdata%\Youtube Playlist Downloader` (just copy paste that into file explorer and it will take you there), the file should be named Errors.txt

**Comment by SpikeOnly** [comment]
had the same issue while launching the program for the first time, here's my error log (sorry, error is in french)

`The object reference is not defined to an instance of an object`
[Errors.txt](https://github.com/shaked6540/YoutubePlaylistDownloader/files/7949416/Errors.txt)

**Comment by shaked6540** [comment]
Thanks, can you also specify what playlist you were trying to download and what settings you were using? 
Also, this usually happens when you don't have permissions to save files in the destination folder, could you try re-running the program as administrator (right click -> run as administrator) and see if the problem occurs again?

**Comment by vgc12** [comment]
hey im sorry for not replying, i was trying to download this playlist https://www.youtube.com/watch?v=CY1Fn3Cw8RA&list=PLByKq_heeaD3HRSpvIceb-1DJh0AJTY7_
if you relaunch it the problem goes away, its only when you launch it for the first time

**Comment by shaked6540** [comment]
That playlist isn't working for me, it shows up as a single video, it might be locked to a specific region

**Comment by shaked6540** [comment]
Closed because of inactivity
