### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by mm9hassan** [shaked6540/YoutubePlaylistDownloader#68]
all Thing download But where is it cant finding in laptop??

**Comment by shaked6540** [comment]
Click on the settings icon near the search bar, and then choose the save location: 
![image](https://user-images.githubusercontent.com/13851815/153667332-62be0b8c-b5d1-4871-95a6-b9ca1a1ea541.png)
![image](https://user-images.githubusercontent.com/13851815/153667364-7bb7b4bf-825f-4205-afb4-d3cb13bcbb37.png)

**Comment by mm9hassan** [comment]
Well I do this not working  Sent from Mail for Windows From: Shaked DahanSent: Saturday, February 12, 2022 1:43 AMTo: shaked6540/YoutubePlaylistDownloaderCc: Hassan; AuthorSubject: Re: [shaked6540/YoutubePlaylistDownloader] Download (Issue #68) Click on the settings icon near the search bar, and then choose the save location:—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by mm9hassan** [comment]
settings not save I go back check its default  Sent from Mail for Windows From: Shaked DahanSent: Saturday, February 12, 2022 1:43 AMTo: shaked6540/YoutubePlaylistDownloaderCc: Hassan; AuthorSubject: Re: [shaked6540/YoutubePlaylistDownloader] Download (Issue #68) Click on the settings icon near the search bar, and then choose the save location:—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by shaked6540** [comment]
Maybe try running the program as administrator, right click->run as administrator

**Comment by mm9hassan** [comment]
Thanks Its working Sent from Mail for Windows From: Shaked DahanSent: Saturday, February 12, 2022 4:20 AMTo: shaked6540/YoutubePlaylistDownloaderCc: Hassan; AuthorSubject: Re: [shaked6540/YoutubePlaylistDownloader] Download (Issue #68) Maybe try running the program as administrator, right click->run as administrator—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
