### ISSUE TITLE
Bug: Download speed seems to be really slow in this app

### ISSUE THREAD

**Issue by Droyk** [shaked6540/YoutubePlaylistDownloader#7]
Well I tried to download 20 videos
and couldn't be able to download a single video with my max internet speed 

If I try to download the same files with youtube-dl I don't have any problem?
please fix it.

**Comment by shaked6540** [comment]
Can you tell me what videos were you trying to download? 
I just checked and I'm getting stable 20MiB/s (my internet speed is 200mbps) 
![image](https://image.prntscr.com/image/25_Ux_BFQECy2mz4c95VMQ.png)

**Comment by Droyk** [comment]
take this for example https://www.youtube.com/watch?v=L8jqGOgCy5M
I have a download speed of 60MB 
![image](https://user-images.githubusercontent.com/15848350/47269370-66124580-d57a-11e8-96ec-3d2a469a152b.png)

**Comment by shaked6540** [comment]
Your download speed is higher than mine, I think this is on youtube's side. I tried downloading the same video and I get 24~MiB/s, which is the max of my internet speed. (200mbps = 25MiB/s) 

Are you sure you're getting faster download speeds with youtube-dl?

**Comment by Droyk** [comment]
Yup and I also use IDM to download files and both of them downloaded the above video at the max speed.

**Comment by shaked6540** [comment]
I will try to investigate this, can you show me the contents of your errors file? you can find it at `%appdata%\YoutubePlaylistDownloader\Errors.txt`

**Comment by shaked6540** [comment]
Closing this because I can't get a reply from @Droyk in over 2 weeks now and I can't replicate the issue.
If you have any new information, reopen the issue
