### ISSUE TITLE
Add numbers for filename

### ISSUE THREAD

**Issue by korenevskiy** [shaked6540/YoutubePlaylistDownloader#72]
There are videos with the same names on the channel. When uploading a list of videos with the same names, these videos overwrite the same file. It is necessary to add the numbering setting so that when the names match, the last digit of the numbering in the file name changes.

**Comment by shaked6540** [comment]
I will try to solve it

**Comment by korenevskiy** [comment]
But, only in the case when the names match inside the same list. But the files themselves are not overwritten. Just add numbering at the time of analyzing the list of titles from the playlist. And then, if the names match, the files are overwritten.

**Comment by shaked6540** [comment]
Should be fixed with the latest update, let me know if it works
