### ISSUE TITLE
In "Bulk download" there is no way to drag

### ISSUE THREAD

**Issue by korenevskiy** [shaked6540/YoutubePlaylistDownloader#73]
In "Bulk download" there is no way to drag the text from the browser address bar with the mouse. And there is also no way to drag the link from the site page. It turns out that first you need to drag everything into Notepad, and then copy it from notepad to the Loader. Why can't it be done right away without intermediaries?

**Comment by shaked6540** [comment]
What do you mean 'drag'? You can copy paste from the browser if thats what you meant; Select the text you want to copy, press CTRL+C and then click the text box in Bulk download and press CTRL+V. 

No need to drag it into notepad

**Comment by korenevskiy** [comment]
I have 2 monitors. I hover my mouse over the link in the site and pull it. I'm NOT dragging an address. I drag the link from the site page. The fact is that dragging the link with the mouse speeds up the work by 3 times compared to activating the address bar, then press Ctrl+A, then press Ctrl+C, then also press Ctrl+V. When the list consists of 50 or 100 links, then this possibility of dragging links into the field speeds up at times.

**Comment by korenevskiy** [comment]
And also it is necessary that when inserting a link Ctrl + V and when dragging. After insertion, a line break was added automatically.

**Comment by shaked6540** [comment]
I will try to make it work, it could take some time because I can't start working on it until the weekend

**Comment by korenevskiy** [comment]
I am grateful to you that you are doing this business at all.

**Comment by shaked6540** [comment]
I tried dragging a link from a website into the bulk download text box and it seems to work, maybe I did not understand what you meant. 

What I tried is to go to a random website, find a link and then drag and drop it into the bulk download text box. It works, I get the link inside the bulk download text box. 

Did you perhaps mean something else?

**Comment by shaked6540** [comment]
I added a newline after pasting or dropping text into the bulk download text box too
