### ISSUE TITLE
Please add button "Reload" for item in list

### ISSUE THREAD

**Issue by korenevskiy** [shaked6540/YoutubePlaylistDownloader#74]

**Comment by shaked6540** [comment]
What do you mean? What reload button, where, and what would it do?

**Comment by korenevskiy** [comment]
![image](https://user-images.githubusercontent.com/6898474/159156289-ba7de567-f05e-43d4-84e2-dc54d4d68721.png)

**Comment by korenevskiy** [comment]
### Maybe immediately add another button. 
To copy the address back to the clipboard. And suddenly there will be a lot of downloads, and it will not be clear what was swinging from where. By opening the link again in the browser, it will be clear what the link is. Copy to clipboard will be a sufficient function.
