### ISSUE TITLE
Not download this link

### ISSUE THREAD

**Issue by korenevskiy** [shaked6540/YoutubePlaylistDownloader#75]
[https://www.youtube.com/channel/UCJ4noxqTyOEnaTEwh03oBVQ/videos](https://www.youtube.com/channel/UCJ4noxqTyOEnaTEwh03oBVQ/videos)

**Comment by shaked6540** [comment]
It works for me, what error are you getting?

**Comment by korenevskiy** [comment]
![image](https://user-images.githubusercontent.com/6898474/159156226-e9e93d90-83c8-4e08-b96b-c9f9ab2082b9.png)

![image](https://user-images.githubusercontent.com/6898474/159156205-395eedc2-fb71-4804-be01-3281909fd1fa.png)

**Comment by korenevskiy** [comment]
But, even with an error message, a new position is added to the list of downloads. In the new position, -42 is visible. But in fact there are only 6 video clips.
![image](https://user-images.githubusercontent.com/6898474/159156371-c6dd6da2-8c89-4877-a922-bf844a789a63.png)

**Comment by korenevskiy** [comment]
This may allow you the opportunity to find out the cause of the error.
![image](https://user-images.githubusercontent.com/6898474/159158297-f5211202-f22c-4e8d-99f3-270c69a0ef6a.png)

**Comment by korenevskiy** [comment]
This may allow you the opportunity to find out the cause of the error.
![image](https://user-images.githubusercontent.com/6898474/159158366-3ea49b15-aecd-4b35-a14f-62d578fc3d2c.png)

**Comment by shaked6540** [comment]
Can you screenshot the settings you're using? The button near the link text box

**Comment by korenevskiy** [comment]
![image](https://user-images.githubusercontent.com/6898474/159257446-39796a99-f2b3-4ada-8882-63ead9c510a6.png)
![image](https://user-images.githubusercontent.com/6898474/159257529-1823863e-5bc5-4753-be72-c03299b93bd6.png)

**Comment by korenevskiy** [comment]
You right.

**Comment by korenevskiy** [comment]
I just unchecked the box opposite 48, but the error persisted. But after writing down the number 0, the download started. What role does the tick play?

**Comment by korenevskiy** [comment]
I just unchecked the box opposite 48, but the error persisted. But after writing down the number 0, the download started. What role does the tick play?

**Comment by shaked6540** [comment]
It shouldn't happen, I will check it and fix it.

**Comment by korenevskiy** [comment]
> It shouldn't happen, I will check it and fix it. 

this is not critical, but if you will fix it, you may want to make a combobox with the select of the sorting method. forward, reverse, by date, or by duration.
for example, download 20 videos only short or only the very first. But the program works. and it can already be used. it is very convenient to drag links. thanks.

**Comment by korenevskiy** [comment]
https://www.youtube.com/watch?v=2F6ZYC4LVoc
https://www.youtube.com/watch?v=xAYowMeszvg
https://www.youtube.com/watch?v=0_G4gZcFgLk
This links not download

**Comment by shaked6540** [comment]
I found the problem but unfortunately it will be a bit hard to fix and since I don't have time I'll not fix it. sorry :( 

The problem is that these videos are missing the audio or video streams. What my program does is download the video only stream, and then the audio only stream and combine them into 1 file. These videos have only muxed videos, meaning videos with audio included. And while that's not an issue, my program then tries to find the 2nd stream and combine it, but its met with an error because the 2nd stream doesnt exist. 

to solve it I'll have to re-write the logic of choosing the video/audio streams and also the handling 

In general, most videos have at least 2 seperate audio and video streams so thats why I choose that approach instead of searching for videos with only 1 stream.

**Comment by korenevskiy** [comment]
And if you do not change the logic of choice. And just use the principle, well, if there is no stream, then you don't need to download it, but download only what is available. And in this case, only what is available will be downloaded.

**Comment by korenevskiy** [comment]
I have a lot of such links, I just wrote 2 of them here, there was no point in writing everything. Thanks. Did you come across such links when using the program? 
When I used the program, I wouldn't even know that there are such links. I had to manually compare the number of videos in the channel with the actual number of files. Since the number number in the program can show the number of thread links found, and not show the number of real ones. I think that you could also have the same videos, but you just didn't know about the presence of such.
