### ISSUE TITLE
yt-dlp

### ISSUE THREAD

**Issue by Davide2009** [shaked6540/YoutubePlaylistDownloader#78]
please add yt-dlp.exe for multi sites

**Comment by shaked6540** [comment]
Sorry, not going to happen.

There are many other yt-dlp GUIs out there, I wanted my program to not be a yt-dlp wrapper and do things on its own.

Here is a list of GUIs you could use: https://www.reddit.com/r/youtubedl/wiki/info-guis 

Good luck :)
