### ISSUE TITLE
multilink

### ISSUE THREAD

**Issue by Davide2009** [shaked6540/YoutubePlaylistDownloader#79]
add code multilink, ex: yt-dlp ecc.

**Comment by shaked6540** [comment]
I already replied to you about it, I'm not adding yt-dlp. If you want yt-dlp go use it. 

 from #78:

> 
> Sorry, not going to happen.
> 
> There are many other yt-dlp GUIs out there, I wanted my program to not be a yt-dlp wrapper and do things on its own.
> 
> Here is a list of GUIs you could use: https://www.reddit.com/r/youtubedl/wiki/info-guis 
> 
> Good luck :)
> 
>
