### ISSUE TITLE
very useful

### ISSUE THREAD

**Issue by Davide2009** [shaked6540/YoutubePlaylistDownloader#80]
Option:
1) Drag and Dorp file .txt ecc.. to Textbox MultipleDownload
2) Save Settings of the files stored in the textbox in order to have them back at the next start
3) Button paste Link or event type: Win32.CopyDataStruct

**Comment by shaked6540** [comment]
Thanks for the suggestions, I don't hace any plans to support these features sadly. You can commission me to add them, check the sponsor section
