### ISSUE TITLE
Metadata is lost when converting to WAV

### ISSUE THREAD

**Issue by stepframe-design** [shaked6540/YoutubePlaylistDownloader#81]
When downloading mp3, everything works great. But when i download WAV, it loses all metadata. Its basically a empty File with only audio and title. 

As i dont really have that much of programming experience, i dont feel qualified to fix that myself. 
I found this: https://trac.ffmpeg.org/ticket/7579
(Im not really shure if you even use ffmpeg)

**Comment by stepframe-design** [comment]
I also found this: https://stackoverflow.com/questions/8081676/how-to-download-a-youtube-video-using-the-youtubes-api
(im not shure if that helps)

**Comment by shaked6540** [comment]
Hi, sorry for the delay, I will try to check it out next week. I'm very busy currently :(

**Comment by stepframe-design** [comment]
Coming back to this, wav just does not support some of the metadata. I use FLAC now
