### ISSUE TITLE
No video, audio only when downloading a playlist

### ISSUE THREAD

**Issue by dp289m** [shaked6540/YoutubePlaylistDownloader#86]
trying to get a playlist to download, seems only audio is getting through.
https://www.youtube.com/playlist?list=PL5BwB5wUDXk3k6EA0-IOIgw8d8VEM_AEQ
Otherwise its working perfectly )

**Comment by Korb** [comment]
@dp289m, what settings exactly do I need to use to download a playlist to audio files? In the settings for each download I see sections General, Video, Audio, Playlist and Filter. In none of them do I see an option to disable video downloading, or disable combining audio with video.
