### ISSUE TITLE
Add feature

### ISSUE THREAD

**Issue by KalpanaChetan** [shaked6540/YoutubePlaylistDownloader#87]
Please add scheduler

**Comment by shaked6540** [comment]
What do you mean?

**Comment by KalpanaChetan** [comment]
Some video downloader  have a schedule download features 

J downloader (window)

1DM (android)

I have free internet between 12 to 6 (night)

It is hard to stay awake till 12 at night 

That is why I use schedule feature 

I have set a time of 12 in the scheduler 

Download starts automatically at 12 o'clock

**Comment by shaked6540** [comment]
Sorry, I'm not going to work on that. If you want, you can code it yourself and create a pull request and I will merge it

**Comment by KalpanaChetan** [comment]
I am very simple user

Github/Developers/Other Things inspire me to learn to code

One day I will learn
