### ISSUE TITLE
Format issues

### ISSUE THREAD

**Issue by SrazerBlade** [shaked6540/YoutubePlaylistDownloader#9]
The latest update only downloads in webm format, no matter what settings are set.

**Comment by shaked6540** [comment]
I'm sorry but I'll not be able to solve this soon. I have joined the army and I will only be back home at weekends so if you need some urgent downloading I suggest using another program (I recommend youtube-dl) 

If you can wait I think I'll be able to fix it this weekend (November 15-17)

**Comment by shaked6540** [comment]
I just got back home and tried to replicate the issue, but I just checked and all formats work for me
Could you please tell me what settings were you using?

**Comment by SrazerBlade** [comment]
I have a feeling it’s a broken setting that has stuck through me uninstalling and reinstalling it because it works perfectly fine for my friend and I see no other reports about it. I'll see if I can figure it out when i get home.

**Comment by shaked6540** [comment]
No, it was my bad, I fixed that bug. it occurred when you checked the "Download clean audio" checkbox and then unchecked it, it wouldn't recognize that you unchecked it

Its fixed now, let me know if it works so I can close this issue
If it doesn't work, give me the link to the video you're trying to download and the full settings you used when downloading

**Comment by SrazerBlade** [comment]
Works flawlessly, keep up the good work!
