### ISSUE TITLE
videos are not downloading

### ISSUE THREAD

**Issue by MinecraftMoments** [shaked6540/YoutubePlaylistDownloader#92]
everything seems to work properly, but the videos are not showing up in the destination folder

**Comment by MinecraftMoments** [comment]
future me note: opened it again in administrator mode and it worked that time

**Comment by shaked6540** [comment]
That happens because they program doesn't have permission to write files to places in the C drive in windows. To solve that problem, either run it as administrator or change the save location to another drive (like D for example)
