### ISSUE TITLE
Consider adding retry feature

### ISSUE THREAD

**Issue by David-Willo** [shaked6540/YoutubePlaylistDownloader#94]
First thanks for the toolkits, it's really helpful.
There would be connection errors on several items when downloading a playlist occasionally and may need to retry the full download again.
Adding  the retry feature would be appreciated  : )

**Comment by shaked6540** [comment]
Hi, great suggestion! 
I will try to work on it in the weekend :)

**Comment by shaked6540** [comment]
I added the feature, hopefully it works as you expected
