### ISSUE TITLE
Setting download from video # untill video # doesn't work as intended. 

### ISSUE THREAD

**Issue by ksiciarz1** [shaked6540/YoutubePlaylistDownloader#97]
![Untitled](https://user-images.githubusercontent.com/47066498/203760086-7900d106-8df9-45cf-9ef3-eecdcf0820c5.png)

When you put anything under download to video # as soon as you close setting tab, the number becomes 0 and instead number download from video # becomes the number you put.

**Comment by Chris0706** [comment]
can confirm

**Comment by shaked6540** [comment]
Should be fixed now, update the program

**Comment by ksiciarz1** [comment]
Yup works. Thanks for quick fix.
