### ISSUE TITLE
When maximizing, it automatically fullscreens, making the taskbar disappear.

### ISSUE THREAD

**Issue by Bummbumm6** [shaked6540/YoutubePlaylistDownloader#98]
Is this because of the program or because of Windows settings or something? I've been trying to find a solution for so long and this is the only program that is still fullscreening.

**Comment by shaked6540** [comment]
I will take a look at it, honestly I never tried maximizing it so I didnt notice it

**Comment by cristianst85** [comment]
I can confirm this behavior.

Not sure if this is relevant, but I have Windows 10 version 22H2 (OS Build 19045.2251) and the latest build of the application from the master branch (commit e24d8b9c).

**Comment by cristianst85** [comment]
I am looking at the code, and the issue seems to be the line below.

https://github.com/shaked6540/YoutubePlaylistDownloader/blob/e24d8b9c85e91c81889320440fe570652b0270ba/YoutubePlaylistDownloader/Skeleton.xaml.cs#L90

Now I am wondering why the `IgnoreTaskbarOnMaximize` was set to `true` in the first place, and it's probably because if we set it to `false` (or remove it altogether), the application goes under the taskbar which is also not good.

**Comment by shaked6540** [comment]
> I am looking at the code, and the issue seems to be the line below.
> 
> https://github.com/shaked6540/YoutubePlaylistDownloader/blob/e24d8b9c85e91c81889320440fe570652b0270ba/YoutubePlaylistDownloader/Skeleton.xaml.cs#L90
> 
> Now I am wondering why the `IgnoreTaskbarOnMaximize` was set to `true` in the first place, and it's probably because if we set it to `false` (or remove it altogether), the application goes under the taskbar which is also not good.

What did you mean by "the application goes under the taskbar"? when I set it to false I can still see the taskbar and and the application

**Comment by cristianst85** [comment]
> What did you mean by "the application goes under the taskbar"? when I set it to false I can still see the taskbar and and the application

It goes under the taskbar a bit (i.e., there is some overlapping going).

This is how it looks on my system.
![image](https://user-images.githubusercontent.com/12585988/206878023-2c672770-2ca0-4a51-9a2b-ffdb9293924c.png)

**Comment by shaked6540** [comment]
I've released an update that should fix it, let me know if it works

**Comment by cristianst85** [comment]
With regards to the original issue, it's better. But the `About` button is still partially out of the screen, but I think we can leave that for another issue. 😄 

![image](https://user-images.githubusercontent.com/12585988/206879215-dceb881d-3192-4e69-9026-375f518ee43b.png)

**Comment by Bummbumm6** [comment]
Great, it works now :)
